### ISSUE TITLE
WebAssembly update?

### ISSUE THREAD

**Issue by dsaf** [dotnet/llilc#1067]
https://github.com/dotnet/llilc/issues/663#issuecomment-118952202

>As you know, Roslyn currently translates C# into MSIL; whilst LLILC is currently focused on compiling MSIL into LLVM bitcode. WebAssembly looks interesting, but clearly needs lots of work before gaining a firm foothold. One key step is obviously getting all popular browsers to interpret/JIT wasm’s binary ASTs, and capitalize on the extra optimizations made possible by emitting the asm.js subset of JS. (Until then, Polyfill will decompile to asm.js). Yes, wasm is being worked on by some “big names” (Google, Microsoft, Mozilla, Apple). We agree it deserves attention from all components of the toolchain. So, LLILC will follow the progress of wasm and consider supporting in due course, as a clearer picture emerges.

https://blogs.windows.com/msedgedev/2016/10/31/webassembly-browser-preview/#8KATEweyuc1KJ3QL.97

https://hacks.mozilla.org/2016/10/webassembly-browser-preview

http://v8project.blogspot.co.uk/2016/10/webassembly-browser-preview.html

The clear picture emerged. What is your progress on this? Thanks.

**Comment by TomMarius** [comment]
Any update?

**Comment by rvhuang** [comment]
I just happened to see this issue. I guess a subset of .NET Standard Library is also necessary if we want to make C# to WebAssembly possible.

**Comment by am11** [comment]
This work has been started here: dotnet/corert#4659. CoreRT compiles HelloWorld wasm.

Docs: https://github.com/dotnet/corert/blob/e6d0a93/Documentation/how-to-build-WebAssembly.md

Duplicate/triplicate of: https://github.com/dotnet/coreclr/issues/5303
