### ISSUE TITLE
How to obtain LLVM IR file from MSIL file? 

### ISSUE THREAD

**Issue by hygeanne** [dotnet/llilc#1095]
Hey guys!

I'm trying to find a manual or guide to tell me how I can use LLILC to generate an LLVM IR file from a MSIL file. Is there a way to do this? I'm not even sure how to use LLILC in general, but I really only need LLILC to perform this function and I've not found anything on this yet. 

Thanks!

**Comment by T0bi-Ethirbirge** [comment]
There's nothing called MSIL file. MSIL stands for Microsoft intermediate language which is used to internally represent dotnet compiled code. You can't import a dotnet assembly into LLVM IR, This project uses LLVM as an alternative to RyuJit to benefit from LLVM optimizations.
