### ISSUE TITLE
Find a way to refer symbolically to the addresses handed out by the EE

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#11]
We get a lot of raw addresses from the EE for things like methods and static fields. For instance:

  %1 = call %System.Text.Encoding addrspace(1)* inttoptr (i64 140733439908056 to %System.Text.Encoding addrspace(1)* (i32)*)(i32 %0)

They make the IR dumps somewhat cryptic. Also these addresses vary from run to run so we have to strip them out when we diff the dumps. Sure would be nice to have names here instead of numbers, like so:

  %1 = call %System.Text.Encoding addrspace(1)*System.Text.Encoding::GetEncoding(i32 %0)

**Comment by Bevinsky** [comment]
Are these addresses invalidated between JIT invocations? In my dumps I have:

    %17 = call %System.AppDomainSetup addrspace(1)* inttoptr (i64 8791367161824 to %System.AppDomainSetup addrspace(1)* (i64)*)(i64 8789766416032)
    
    ... Code ...
    
    ; In a different method:
    %13 = call %System.IndexOutOfRangeException addrspace(1)* inttoptr (i64 8791367161824 to %System.IndexOutOfRangeException addrspace(1)* (i64)*)(i64 8789766911584)

I don't see how these can point to the same location.

**Comment by AndyAyersMS** [comment]
These are both from a single instance of CoreRun I take it? I'm reasonably sure in these simple tests that code addresses are not recycled at runtime, though there are some ways it can happen in more complex scenarios (eg an assembly is unloaded).

It could be that this is a common entry point to the runtime, say one of the helpers -- you'll notice the parameter passed to the calls is different so there is the potential for variant behavior (and possibly argument-dependent return types). For instance this might be the newobj helper and the parameter is the type of object to construct.

**Comment by Bevinsky** [comment]
All right, I had a more detailed look at the code and I see what you mean.

I think it would be acceptable to have the client resolve these pointer conversions and store them in globals, like so:

    @"System.Text.Encoding::GetEncoding" = global %System.Text.Encoding addrspace(1)* (i32)* inttoptr (i64 140733439908056 to %System.Text.Encoding addrspace(1)* (i32)*

The only issue with this is that these globals cannot be overloaded, so if there is a static method with a different set of arguments, another global with a slightly different name (such as "_2" or "(i32)" appended) would have to be created. It would seem best to include the entire function definition in the name, but it seems a bit redundant and lines will get sort of long.

**Comment by JosephTremoulet** [comment]
By my reading of [the language reference manual's section on globals](http://llvm.org/docs/LangRef.html#global-variables), a global with the pointer conversion as an initializer would define a global whose *contents* are a pointer to the function, meaning that we'd need to load the global before invoking the function pointer at each callsite (or mark the global `constant` so that the optimizer can optimize away the load but then we're back to illegible IR).  I'd rather hope we could declare these as [functions](http://llvm.org/docs/LangRef.html#functions) and maybe there's an appropriate way to override [`findSymbol`](http://llvm.org/doxygen/classllvm_1_1RTDyldMemoryManager.html#aa2b25d3890b3cd7c4af0fb03017c06c7) to return the appropriate address to the loader.

**Comment by AndyAyersMS** [comment]
Yeah, I was hoping to find a "named constant" construct but at least in my cursory search, didn't see anything that would work. But I very well might have missed it. 

Another possibility is to keep a side table of address->name and then hook into the IR dumper somehow and override what it is doing.

**Comment by russellhadley** [comment]
@AndyAyersMS could an 'alias' work?  They will introduce a new name for a constant expression.

**Comment by Bevinsky** [comment]
@JosephTremoulet Hm, I was hoping that defining the global as a function pointer would let you simply call it directly. Perhaps that wasn't the case after all. I thought in the worst case scenario, we could just load the pointer from a constant as you say, and let LLVM's constant folding take care of it. It would only result in a single extra instruction AFAICT.

@russellhadley Can aliases be taken on constant expressions? I was under the impression that aliases were only for other globals.

**Comment by russellhadley** [comment]
@Bevinsky I'm just going from this in the documentation:

"Aliases have a name and an aliasee that is either a global value or a constant expression."

**Comment by Bevinsky** [comment]
@russellhadley Oh, how did I miss that? I was focusing on the syntax example which specifies `@<Aliasee>`, which led me to believe that only another global could be aliased.

**Comment by russellhadley** [comment]
@Bevinsky, more eyes are better.  :)  I just hope it works.

**Comment by Bevinsky** [comment]
Well, I did a quick toy example test in llc on this:

	@test2 = alias i32(i8*, i32)* inttoptr (i64 1241424244242 to i32(i8*, i32)*)

	define i32 @testt(i32 %x, i8* %y) {
	entry:
	  %val = call i32 @test2(i8* %y , i32 %x)
	  ret i32 %val
	}

and it seems to work. The difference I'm seeing in compiled results between this and inlining the value is that here, it calls a symbol named test2:

		movl	%ecx, %eax
		movq	%rdx, %rcx
		movl	%eax, %edx
		callq	test2
                ...
		.globl	test2
	test2 = 1241424244242

and with the value in the call directly, it does this:

		movabsq	$1241424244242, %r8     # imm = 0x1210AA6AE12
		movq	%rdx, %rcx
		movl	%eax, %edx
		callq	*%r8

I'm no expert, but it doesn't seem like LLVM should have any problem with this. I could give it a shot and see how it works in LLILC.

**Comment by AndyAyersMS** [comment]
That looks promising. 

The names for regular methods are stored in the call info, at least for debug builds. There is also a way to get names for the helper calls (which again might only work in debug builds).

**Comment by pgavlin** [comment]
FWIW, assembling the output and dumping the binary gives:

```
[pgavlin@muninn misc]$ objdump -t -d -r alias.o

alias.o:     file format elf64-x86-64

SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 alias.ll
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 l    d  .data  0000000000000000 .data
0000000000000000 l    d  .bss   0000000000000000 .bss
0000000000000000 l    d  .note.GNU-stack        0000000000000000 .note.GNU-stack
0000000000000000 l    d  .eh_frame      0000000000000000 .eh_frame
0000000000000000 g     F .text  000000000000000f testt
000001210aa6ae12 g       *ABS*  0000000000000000 test2



Disassembly of section .text:

0000000000000000 <testt>:
   0:   50                      push   %rax
   1:   89 f8                   mov    %edi,%eax
   3:   48 89 f7                mov    %rsi,%rdi
   6:   89 c6                   mov    %eax,%esi
   8:   e8 00 00 00 00          callq  d <testt+0xd>
                        9: R_X86_64_PC32        test2-0x4
   d:   5a                      pop    %rdx
   e:   c3                      retq
```

**Comment by AndyAyersMS** [comment]
I don't believe this invalidates the general approach.

In the above, we'd need to pass the "large memory model" flag into LLC so it is not tempted to use 32 bit offsets, and then do something similar for LLILC.

**Comment by pgavlin** [comment]
I agree--as you point out, we just need to find a way to make sure that appropriately-sized relocations are used.

**Comment by pgavlin** [comment]
Okay, passing `-code-model=large` to `llc` gives:

```
	.text
	.file	"alias.ll"
	.globl	testt
	.align	16, 0x90
	.type	testt,@function
testt:                                  # @testt
	.cfi_startproc
# BB#0:                                 # %entry
	pushq	%rax
.Ltmp0:
	.cfi_def_cfa_offset 16
	movl	%edi, %eax
	movabsq	$test2, %rcx
	movq	%rsi, %rdi
	movl	%eax, %esi
	callq	*%rcx
	popq	%rdx
	retq
.Lfunc_end0:
	.size	testt, .Lfunc_end0-testt
	.cfi_endproc


	.globl	test2
test2 = 1241424244242
	.section	".note.GNU-stack","",@progbits
```
