### ISSUE TITLE
Get single test work flow smooth

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#118]
Current test harness is already good with bulk BuildTest and RunTest. But the work flow to add single new test case or work with single test case is not convenient. This is largely due to CoreCLR test assets does not support that. See if CoreCLR test assets can be enhanced or any other solution.

**Comment by AndyAyersMS** [comment]
@richford we have this now, right? Is it documented?

**Comment by richardlford** [comment]
The ability to run a single test is documented and uses either the llilc_run.py or the make_sln.py script. However how to add a new test is not yet documented. This last week I have been studying the test project files and believe I know what is needed to add a new test. I'm planning to test that out and document it in the next day or so.
