### ISSUE TITLE
Document reader.h: Interface to GenIR defined EHRegion structure

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#145]
Document using Doxygen markup, the items rgnListGetNext through rgnSetCatchClassToken in the reader.h file.

**Comment by AndyAyersMS** [comment]
Will hold of on this one pending the @JosephTremoulet 's EH work. Many of these may be altered or no longer needed.

**Comment by AndyAyersMS** [comment]
Again deferring on this, pending EH work.

**Comment by russellhadley** [comment]
Moving to Joe as EH related.
