### ISSUE TITLE
Reader: implement tail calls

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#191]

**Comment by erozenfeld** [comment]
We now hit these in lots of CoreCLR tests. Most of them in JIT\Methodical\tailcall

**Comment by erozenfeld** [comment]
Looks like the existing LLVM tail annotations aren't enough for implementing tail.call.
`musttail` has a constraint that the caller and callee signatures must match. That worked for implementing jmp but tail.call only requires return types to be compatible.
`tail` guarantees the optimization to occur only if the caller and the callee have the calling convention fastcc (and some platform-specific constraints are met).

**Comment by pgavlin** [comment]
@erozenfeld it might be worth looking into what ghc does here.

**Comment by erozenfeld** [comment]
It turns out that tail call optimization is guaranteed for their calling convention as well:
http://llvm.org/docs/CodeGenerator.html#tail-call-optimization
Tail call optimization, callee reusing the stack of the caller, is currently supported on x86/x86-64 and PowerPC. It is performed if:

* Caller and callee have the calling convention fastcc, cc 10 (GHC calling convention) or cc 11 (HiPE calling convention).
* The call is a tail call - in tail position (ret immediately follows call and ret uses value of call or is void).
* Option -tailcallopt is enabled.
* Platform-specific constraints are met.

**Comment by erozenfeld** [comment]
So called sibling call optimization may be good enough for us.
http://llvm.org/docs/CodeGenerator.html#sibling-call-optimization

Sibling call optimization is a restricted form of tail call optimization.
Unlike tail call optimization described in the previous section, it can be
performed automatically on any tail calls when ``-tailcallopt`` option is not
specified.

Sibling call optimization is currently performed on x86/x86-64 when the
following constraints are met:

* Caller and callee have the same calling convention. It can be either ``c`` or
  ``fastcc``.

* The call is a tail call - in tail position (ret immediately follows call and
  ret uses value of call or is void).

* Caller and callee have matching return type or the callee result is not used.

* If any of the callee arguments are being passed in stack, they must be
  available in caller's own incoming argument stack and the frame offsets must
  be the same.

**Comment by erozenfeld** [comment]
@russellhadley please reassign as appropriate

**Comment by russellhadley** [comment]
@AndyAyersMS Assigning since this overlaps with the tailcall work you're doing now.

**Comment by AndyAyersMS** [comment]
Have returned to this and have it mostly coded up -- debugging now.

We classify calls as tail/notail in the reader, let LLVM do the sibling call opt where it can. I can see it kicking in, which is cool. Must still be missing a legality check though.

**Comment by AndyAyersMS** [comment]
Found a bug in LLVM -- when it goes to readjust the stack in the "epilog" it calls `findDeadCallerSavedReg` which does not have the right reg sets for our calling convention. So it makes a bad choice...
```
push        rax  
mov         qword ptr [rsp],0  
mov         qword ptr [rsp],rcx  
mov         rcx,qword ptr [rsp]  
mov         rax,7FD32BFF638h  
xor         edx,edx  
xor         r8d,r8d  
pop         rsi                   // oops
jmp         rax  
```
Worked around this but there are still more issues to sort through....

**Comment by AndyAyersMS** [comment]
Issues fixed, things looking good. Will have to push the LLVM change out first though.

**Comment by AndyAyersMS** [comment]
LLVM fix is (out for review)[http://reviews.llvm.org/D14878].

**Comment by AndyAyersMS** [comment]
With that fix and my changes, I can pass the local windows tests. Still need to see how this interacts with EH and GC, and try it on Linux...

**Comment by AndyAyersMS** [comment]
LLVM fix is now in the main LLVM tree. Now it needs to show up in our MS branch...
