### ISSUE TITLE
Reader: support for synchronized methods

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#271]
See this [TODO](https://github.com/dotnet/llilc/blob/73ce7a1cee4a971ea7bb5875c53e7f8c83ae6cb6/lib/Reader/readerir.cpp#L329-L332)

**Comment by erozenfeld** [comment]
#458 adds enough to unblock HelloWorld. We insert lock acquire on entry and lock release on returns. The remaining work is adding try/fault for the entire method so that we can release the lock on unhandled exceptions.

**Comment by AndyAyersMS** [comment]
@JosephTremoulet maybe this is something you can pick up down the road?

**Comment by JosephTremoulet** [comment]
Sure
