### ISSUE TITLE
Implement support for passing options to the JIT

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#277]
There are a number of [configuration/option settings](https://github.com/dotnet/llilc/blob/73ce7a1cee4a971ea7bb5875c53e7f8c83ae6cb6/include/Reader/reader.h#L147-L187) for the JIT.

We need to hook these up so there is some way to enable them.

**Comment by russellhadley** [comment]
Base implementation to support options is in.  Closing this and opening targeted issues at each option we want to support.
