### ISSUE TITLE
GC:Handle pinned pointers

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#29]
The CoreCLR GC requires that pinned pointers be reported specially.

**Comment by swaroop-sridhar** [comment]
To support pinning, we’ll need to add some Pinning intrinsics to LLVM, demarcate the pinning boundaries:
i.	Have GCCast like controlled casts that allow for integer <-> pointer conversion
ii.	Ensure that the pinned pointers do not move beyond the safepoints outside the pinned zone
iii.	Note the slots containing the pinned pointers, and report them to the GC.
Details of this design are still to be worked out

**Comment by JosephTremoulet** [comment]
> Have GCCast like controlled casts that allow for integer <-> pointer conversion

I would have thought that:
 1. we could use addrspacecast for unmanaged pointer <-> gc pointer conversions
 2. we could use inttoptr/ptrtoint for int <-> unmanaged pointer conversions
 3. we could decompose int <-> gc pointer conversions as int <-> unmanaged pointer <-> gc pointer conversions

Does that not work?

**Comment by JosephTremoulet** [comment]
> add some Pinning intrinsics to LLVM, demarcate the pinning boundaries

This assumes we can identify the "pinning boundaries", which are stores to locals with the `pinned` attribute.  It seems [the ECMA spec](http://www.ecma-international.org/publications/standards/Ecma-335.htm) specifically allows pinned locals of type `O` (II.23.2.9 paragraph 2), and presumably such locals could have their address taken and a conservative implementation would have to assume that any `stind` via managed pointer to object reference might modify a pinned local.

I would be ok with assuming this doesn't happen (or at least isn't guaranteed to have optimizations allow for it to happen), and I think C# only ever generates pinned locals of type `&` (which can't have their address taken), and in turn assuming that modifications of pinned locals only happen at `stloc`s that directly reference them, but I think it's worth make a conscious choice about that.

It also might be worth checking what other JITs have done, I wouldn't be surprised if they effectively make the same assumption.

**Comment by JosephTremoulet** [comment]
> Ensure that the pinned pointers do not move beyond the safepoints outside the pinned zone

Likewise for any dereferences of unmanaged pointers that we can't prove don't point to the pinned objects.  I'd imagine we'll be assuming conservative aliasing for such unmanaged pointer dereferences and so can constrain these dereferences by modeling the pin operation with wide enough side-effects, but it'll be worth making sure.

**Comment by swaroop-sridhar** [comment]
@JosephTremoulet  For GCCast -- yes, the intrinsic should convert between managed and unmanaged pointers. Thanks for the correction.

**Comment by JosephTremoulet** [comment]
@swaroop-sridhar: what I meant to ask was whether the existing `addrspacecast` opcode could be used for those conversions, or do we really need a new intrinsic?

**Comment by swaroop-sridhar** [comment]
The reason I said GCCast, is that the intrinsic may need some additional arguments to ensure read/write dependencies to constrain motion wrt the pinning boundaries. I'll think about it a bit more.

**Comment by swaroop-sridhar** [comment]
Discussion on the topic
https://onedrive.live.com/redir?resid=AC987D2E0C9397C1!53301&authkey=!AIUbw7-Hx75bk_0&ithint=file%2cdocx

**Comment by JosephTremoulet** [comment]
Looks like I had things backwards.  [Per Chandler](http://lists.llvm.org/pipermail/llvm-dev/2015-September/090180.html), addrspacecast is (spec'ed to be) quite benign, so yes we'll need some sort of GCCast for the constrained casts like you said originally.

**Comment by swaroop-sridhar** [comment]
Fixed by https://github.com/swaroop-sridhar/llilc/commit/90265ac37eb14a7d8371cff519d99466a4c94acd
