### ISSUE TITLE
Reader: defer lowering of certain constructs

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#292]
There will ultimately be many candidates but for now we can look at some of the float/int conversion operations. LLVM has opcodes for these that will lower to calls to the CRT; we want them to lower to calls to EE helpers instead.

See [TODO](https://github.com/dotnet/llilc/blob/73ce7a1cee4a971ea7bb5875c53e7f8c83ae6cb6/lib/Reader/readerir.cpp#L1985-L1986).

**Comment by russellhadley** [comment]
@pgavlin Didn't we do this already as part of the CLR env work?

**Comment by pgavlin** [comment]
No: this requires that we specify a `TargetLibraryInfo` instance to the backend. There is not currently any way to do this outside of changing our ORC layers s.t. we can add passes the pass manager.
