### ISSUE TITLE
Reader: possibly use pc-relative call forms

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#296]
Currently we always use full 64-bit values for call targets. In some cases we may know the call target is within a 32-bit distance from the call instruction, so we might be able to use a PC relative form.

See [TODO](https://github.com/dotnet/llilc/blob/73ce7a1cee4a971ea7bb5875c53e7f8c83ae6cb6/lib/Reader/readerir.cpp#L2836-L2839).

**Comment by pgavlin** [comment]
@Bevinsky FYI. I think that this might crop up during the work you've been doing to enable symbol aliases.
