### ISSUE TITLE
GC: Translate from stack map format to the input format for the GC info encoder

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#31]
The Statepoint work will produce LLVM stack maps at each safepoint. We need to translate this information into the format needed by the GC info encoder.

**Comment by swaroop-sridhar** [comment]
The expectation for this work item is that a few functions build/run with precise GC.
We verify this by:
(1) Examine the GCTable dumps and determine correct wrt assembly code
(2) Debug through the runtime to make sure that a collection happens successfully after scanning the roots from the LLILC generated GC-tables.

Full test pass is covered by issues: #669 and #670
