### ISSUE TITLE
GC-pointers cannot reside in registers across pinvoke calls

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/llilc#313]
Because the actual GC-pointers would be saved in the stacks of the native compiled code they would not be reported or necessarily discoverable by the GC stack walker. Therefore GC pointers are required to be in memory across direct pinvoke calls.

pinvoke can be identified by callInfo->methodFlags that is in the CORINFO_CALL_INFO field from the EE interface eeGetCallInfo.

Ideally the LLVM register allocator would shrink-wrap the spills around such call sites, but this might require recognizing GC lifetime slate during compilation. An interim solution might be to mark all locals and parameters as volatile when the method contains pinvoke. I'm not sure whether disabling optimizations would be sufficient since you might be temporary GC lifetimes live across the pinvoke depending upon the order of evaluation. There are probably other options that are available as well.

This is probably something that has to be fixed on the hello world bring up path since there are some pinvoke on startup path iirc.

**Comment by pgavlin** [comment]
We currently have a crude solution in place in LLVM that simply forces spills/restores of all callee-saved GPRs at unmanaged calls. https://github.com/Microsoft/llvm/issues/26 tracks improving this.
