### ISSUE TITLE
Add line info jit debug reporting for LLILC

### ISSUE THREAD

**Issue by adiaaida** [dotnet/llilc#318]
Communicate MSIL offset -> native offset back to the CLR EE.

**Comment by russellhadley** [comment]
@adiaaida is there a way we can validate the bit we have done and check it in?  I'm fine if this is done incrementally.

**Comment by adiaaida** [comment]
Yes. I'll talk with the debugger people and see if I can get this validated. I'm worried about the code that I had to comment out, so we'll need to take a closer look at why that's happening too.

**Comment by russellhadley** [comment]
@adiaaida can you add some notes here on the current status?

**Comment by adiaaida** [comment]
This has been checked in (#647)

**Comment by russellhadley** [comment]
@adiaaida can this be closed now?

**Comment by adiaaida** [comment]
closed with #647
