### ISSUE TITLE
Share throw blocks

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/llilc#327]
Currently we generate a separate throw block (block which calls the appropriate helper to raise an exception) for each operation that needs an exception check (loads, stores, array bounds check, divide-by-zero, overflow).  This approach favors debuggability (when a check fails, someone debugging the code can determine which check failed).  To favor codesize, we could use the same throw block for any two exception checks that raise the same kind of exception and are in the same protected region.  We should decide when to use which policy and implement that decision.  The production jit uses one or the other strategy depending whether the EE specified `CORJIT_FLG_DEBUG_CODE` for the method being compiled, though for null dereference it uses machine traps, so a faulting dereference can always be traced back to the load/store that failed.

See [this note](https://github.com/dotnet/llilc/blob/3f8d560a774f5a82fe3fc3687738a892dd573fc6/lib/Reader/readerir.cpp#L3781-L3784).

**Comment by AndyAyersMS** [comment]
LLVM will merge throw blocks when optimizing. However in pathological cases (eg `JIT\jit64\opt\cse\HugeArray` and friends the optimization takes ~100 seconds. So we're probably better off with changing the codegen in the reader.

However, there's also an optimization to turn null checks back into explicit throws in the machine code layer of LLVM. The pattern looks fairly fragile and probably won't work for our cases out of the box. If/when we choose to rely on this we might need to generalize it to handle the case where there is a join on the exceptional path.

**Comment by JosephTremoulet** [comment]
> an optimization to turn null checks back into explicit throws

I'm unfamiliar with that.  What's it called / where is the code?  How does it know what a throw looks like?

**Comment by AndyAyersMS** [comment]
```
-enable-implicit-null-checks                        - Fold null checks into faulting memory operations
```
Code is [here](https://github.com/Microsoft/llvm/blob/master/lib/CodeGen/ImplicitNullChecks.cpp)

**Comment by JosephTremoulet** [comment]
Sorry, I misread your previous comment.  Yes, I knew about that one.

You're right that it won't work for our cases out of the box, in that it expects the machine trap handler to just transfer control to an explicit throw block in the function, whereas the CoreCLR machine trap actually throws the null reference exception.  So we'll have to extend it to (optionally) match a bigger pattern which includes a call to CORINFO_HELP_THROWNULLREF (and work out how to communicate to the optimization how to recognize those calls).  And yes when we do that extension we'll want it to be cool with it if the edge to the throw block is a join and not remove the successor unless we're removing its last predecessor.
