### ISSUE TITLE
LLVM verifier errors should be treated as test failures

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#335]
Or at the very least treated like other point method failures.

We're still silently letting this pass by.

**Comment by pgavlin** [comment]
Is this finished?

**Comment by erozenfeld** [comment]
I added an assert that verification succeeded in abb614c73bc80f6bb469d8983fbef251bdd34120
but it was removed in  93b82adac634fe93c7b798f6d2a855b601ee9310. @russellhadley Was it removed accidentally?

**Comment by russellhadley** [comment]
Yes.  I made the wrong guess on merging and dropped it.  There should be no issue adding it back.
