### ISSUE TITLE
Consistently use `nullptr` instead of `NULL` or `0`

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#346]
We should be consistent about how we refer to null pointers in our code.

**Comment by pgavlin** [comment]
Is this finished? grepping for NULL doesn't turn up anything relevant.

**Comment by AndyAyersMS** [comment]
I haven't looked for the zero cases yet, so will leave this open.

**Comment by russellhadley** [comment]
@AndyAyersMS do you want me to take this one?

**Comment by AndyAyersMS** [comment]
Sure.
