### ISSUE TITLE
Improve experience when tests fail

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#391]
When testing a new jit it's often the case that tests will fail.

Currently when this happens there is a ton of output written to the console, none of which is interesting or particularly useful. Instead failures should be summarized with details available in files or similar. 

What's more important is to provide a clear repro instructions for the failing tests, since typically the next thing that must happen is to rerun one or more of the failing tests under the debugger.

**Comment by krk** [comment]
There is 30 minutes of non-stop console output while running the tests.
