### ISSUE TITLE
Investigate LLILC GC test case failures

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#420]
83 GC related test cases were just added to CoreCLR repository.
12 of them cannot run with LLILC at this point. Investigate the causes.

**Comment by AndyAyersMS** [comment]
The coff issue is likely that we try to call memcpy. We can't trust llvm memcpy yet.

**Comment by AndyAyersMS** [comment]
Looked at case 2 a bit more. It's actually __chkstk from the prologue, since these tests have large value types on the stack. My upcoming fix for alloca should fix these too.

**Comment by AndyAyersMS** [comment]
First bit of the alloca work is in, but we'll need microsoft/llvm#23 before the test cases in category 2 pass.

**Comment by AndyAyersMS** [comment]
Am going to revisit these.

**Comment by AndyAyersMS** [comment]
```
JIT\jit64\gc\misc\eh1.cmd -- EH
JIT\jit64\gc\misc\funclet.cmd -- Passes, but skips Test.Main with "direct unmanaged call"
JIT\jit64\gc\misc\fgtest1.cmd -- EH
JIT\jit64\gc\misc\fgtest2.cmd -- EH
JIT\jit64\gc\misc\structfpseh5_1.cmd -- EH
JIT\jit64\gc\misc\structfpseh6_1.cmd -- EH
JIT\jit64\gc\regress\vswhidbey\339415.cmd -- Passes
JIT\jit64\gc\regress\vswhidbey\143837.cmd -- EH
```

`funclet` is actually failing because of an __arglist call. This is not supported on CoreCLR so we should remove the test.
