### ISSUE TITLE
[Question] Will llilc be built on top of coreclr

### ISSUE THREAD

**Issue by zgxnet** [dotnet/llilc#428]
It seems that llilc is a replacement for ryujit. Will it be built directly on coreclr, or it will fork a branch of coreclr?

**Comment by JosephTremoulet** [comment]
The llilc jit builds directly on coreclr.

**Comment by russellhadley** [comment]
Also, LLILC not a replacement of ryujit.  Ryujit is very tuned for Windows and Linux on x64 for app startup time and perf but will have a harder time going to more targets. It's a very specific source base we expect to use in particular scenarios.  The LLILC/LLVM work is complimentary, in that it aims to provide a code generator that can extend C#'s reach to new targets and platforms - though it might not be at app startup time (LLVM is a slower code generator than ryujit).  In particular we're focusing more on the AOT side though we're bringing up the JIT as a way to validate the MSIL translation and functionality.

**Comment by AndyAyersMS** [comment]
@zgxnet did the above answer your questions?

**Comment by zgxnet** [comment]
@AndyAyersMS Thanks for the answer. It is great. 
Another concern is that currently .net jit produces less effective code compared to C++, sometimes even slower than java. Can the use of LLVM give .net a comparative performance as C++? I will really appreciate if llilc can greatly improve the performance.

**Comment by AndyAyersMS** [comment]
One of the project goals is to provide excellent performance. So yes it's on the radar. 

We know from past experience that when optimized properly, the performance of managed languages like C# can be quite competitive with C++.

There is lot of work ahead on this front and others. So stay tuned, or jump in and help us out.

**Comment by AndyAyersMS** [comment]
@zgxnet any other questions we can answer here?

**Comment by zgxnet** [comment]
@AndyAyersMS Thanks.
I have another question. Will llilc support Desktop CLR?
It seems that llilc is a full functional jit and Desktop / core CLR actually share the same code base and it is reasonable to make llilc a drop in replacement of ryujit.

**Comment by jkotas** [comment]
llilc will not support Desktop CLR.

If you try hard, you may be able to make it work, but the such configuration is absolutely unsupported.

**Comment by pgavlin** [comment]
@zgxnet I'm going to go ahead and close this now--please let me now if I'm mistaken in doing so.

**Comment by zgxnet** [comment]
I just wonder why llilc will not support desktop CLR. Is there a particular reason for this? It seems straightforward to support it.

**Comment by zgxnet** [comment]
Another concern. It seems that ryujit suffers from the fact it does not cache field values in registers, which makes it impossible to be as fast as C++. Will llilc change this?

**Comment by jkotas** [comment]
@zgxnet  llilc is focused on .NET Core. We want to run fast with it, focus on cross platform, without worrying about desktop CLR. Desktop CLR is pretty complex product. Supporting it alternative code generator like llilc for it is not straightforward.
