### ISSUE TITLE
Wiki has outdated build instructions

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/llilc#432]
The build instructions on [this page](https://github.com/dotnet/llilc/wiki/Dev-Env-and-Test-Harness) are obsolete.  The instructions on the [Getting Started For Windows](https://github.com/dotnet/llilc/wiki/Getting-Started-For-Windows) page are correct and current.  The two should agree, or probably we should just have one copy of the build instructions on the wiki.

**Comment by AndyAyersMS** [comment]
@libengu can you please fix this when you get a chance. it is confusing.

**Comment by libengu** [comment]
I will update this directly to using llilc_runtest and llilc_checkpass when llilc_checkpass is in. Getting close.

**Comment by libengu** [comment]
Page https://github.com/dotnet/llilc/wiki/Testing is added for testing instructions. It will be effective after PR https://github.com/dotnet/llilc/pull/452 is merged. @AndyAyersMS @adiaaida Could you please take a look at the PR.

Page https://github.com/dotnet/llilc/wiki/%5BDeprecated%5D-Dev-Env-and-Test-Harness is marked as deprecated now. But I still keep it there for reference.

**Comment by JosephTremoulet** [comment]
Thanks for the updates.  I don't understand why keep the old one for reference, though.  We could always dig it out of the history in the wiki repo if we needed to.
