### ISSUE TITLE
Refactor options to incorporate the existing options globals in reader.h

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#438]
We should split the options object into a base part and a client part, and make the base part visible in the reader layer. Then fold in the existing EnvConfig* / HasEnvConfig* globals to reside therein.

The client should still be responsible for figuring out how to set options. The reader part should be query only.

**Comment by russellhadley** [comment]
I can do the mod pretty quickly.

**Comment by russellhadley** [comment]
Added spilt options handling.  Still more to be done to add in individual options but the core is there.
