### ISSUE TITLE
Find better way to exclude failing tests

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#466]
Our current technique for excluding failing tests is to delete the tests after building them. This is a bit fragile since the tests are also built when building the CoreCLR -- it also makes it painful to investigate the failing tests.

We need to find a better method.

**Comment by libengu** [comment]
CoreCLR PR https://github.com/dotnet/coreclr/pull/802 and LLILC PR https://github.com/dotnet/llilc/pull/505 should handle the issue.

**Comment by libengu** [comment]
Both PR merged. Close the issue.
