### ISSUE TITLE
Investigate 6 methods excluded when building Roslyn

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#470]
To get to the end of baby Roslyn compilation we have to exclude 6 methods. It's likely that we generate bad code for them.

System.Reflection.RuntimeParameterInfo.GetParameters (one of the overloads)
System.Reflection.CustomAttributeData.GetCustomAttributeRecords
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.HandleReturn
BasicBlock.SetBranchCode
MemberInfoCache`1[__Canon][System.__Canon].PopulateProperties (one of the overloads)
System.Reflection.Associates.AssignAssociates (one of the overloads)

**Comment by erozenfeld** [comment]
Bad code in System.Reflection.CustomAttributeData.GetCustomAttributeRecords is caused by us not zero initializing locals (in that method a local struct wasn't zero-initialized). I'm surprised this didn't cause failures in HelloWorld.

**Comment by erozenfeld** [comment]
I have a fix for local initialization, will send a PR on Friday.
In addition to System.Reflection.CustomAttributeData.GetCustomAttributeRecords, lack of local zero initialization causes bad codegen in 3 other methods: MemberInfoCache`1[__Canon][System.__Canon].PopulateProperties, System.Reflection.RuntimeParameterInfo.GetParameters, and System.Reflection.Associates.AssignAssociates. The other two methods still need to be investigated.

**Comment by roterdam** [comment]
What is "baby Roslyn"? I want to try out LLILC with Roslyn but all open issues are talking about to a baby version of Roslyn.

**Comment by russellhadley** [comment]
We've got a stripped down version that we've been playing with to flush out issues called baby Roslyn but are planning to move to the full Roslyn on CoreCLR soon - maybe next week (It's in the pipeline to go open.) @erozenfeld is there anything that can be run off the GitHub sources/packages right now?  (sorry @roterdam work in progress - we're working to get this test case harnessed up on GitHub)

**Comment by roterdam** [comment]
I was interested in knowing what baby Roslyn is  what is missing from full Roslyn, it helps put perspective on why you are doing things the way you do them.

Thanks @russellhadley - great work for bringing this open.

**Comment by russellhadley** [comment]
@roterdam "baby Roslyn" has the needed facilities to do command line compilation, so it's a lot of Roslyn but it's missing he ability to do the dynamic plug in handling.  It's a pretty big baby.  We'll get something out there with some stats on what's working pretty soon here.  Thanks for the patience.

**Comment by erozenfeld** [comment]
Fixes for #495 and #517 take care of bad code generated for these 6 methods.
