### ISSUE TITLE
Investigate Inline test case failures

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#487]
39 inlining optimization test cases were added in CoreCLR repo in https://github.com/dotnet/coreclr/pull/776. 3 of them has issue if run with LLILC. Investigate the cause. 
Inline_Handler
Inline_Vars
Inline_Throw

**Comment by AndyAyersMS** [comment]
Will investigate.

**Comment by AndyAyersMS** [comment]
```
JIT\opt\Inline\Inline_Handler.cmd -- EH
JIT\opt\Inline\Inline_Vars.cmd -- Passes
JIT\opt\Inline\InlineThrow.cmd -- EH
```
