### ISSUE TITLE
Reader: support direct unmanaged calls.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#499]

**Comment by erozenfeld** [comment]
We hit these in the following CoreCLR tests:

JIT\Methodical\varargs\callconv\gc_ctor_il_d
JIT\Methodical\varargs\callconv\gc_ctor_il_r
JIT\Methodical\varargs\callconv\val_ctor_il_d
JIT\Methodical\varargs\callconv\val_ctor_il_r
JIT\Methodical\varargs\misc\Dev10_615402
JIT\Methodical\varargs\misc\Dev10_615402
JIT\Regression\CLR-x86-EJIT\V1-M12-Beta2\b26323\b26323
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b16423\b16423
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28901\b28901
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b30838\b30838
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b30864\b30864
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b32374\b32374
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b35784\b35784
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b36472\b36472
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b37598\b37598
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b46867\b46867
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b31745\b31745
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b31746\b31746
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b37646\b37646
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b41852\b41852
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b88793\b88793
JIT\Regression\CLR-x86-JIT\V1-M13-RTM\b91248\b91248
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b409748\b409748

**Comment by AndyAyersMS** [comment]
I'll take a look at this one.

**Comment by AndyAyersMS** [comment]
These are all cases where there is a callee that has varargs but never actually looks at the arguments passed varadically (that is, no `arglist` opcode appears in the callee). We need to exclude these tests as this feature is not supported on CoreCLR.

**Comment by russellhadley** [comment]
@AndyAyersMS can this be closed?

**Comment by AndyAyersMS** [comment]
I think so -- there are possibly  call cases we can't handle but we don't have any tests that expose them. We can open a new issue when we come across these.
