### ISSUE TITLE
Reader: resolve issues with inlining calls to methods that contain unmanaged calls.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#500]
Methods with unmanaged calls contain code that should not be duplicated when inlining. This must be taken into account, as inlining such methods is otherwise likely to produce incorrect results.

**Comment by JosephTremoulet** [comment]
Would it be possible to defer insertion of the "code that should not be duplicated" (this is some prolog/epilog setup/cleanup, yes?) until some point after inlining (like frame setup)?

**Comment by pgavlin** [comment]
Probably, yes. This is something that Russ and I discussed a bit offline.

**Comment by pgavlin** [comment]
What we'd likely do is add a pass that runs at least after the inliner but before ISel that inserts the appropriate IR.
