### ISSUE TITLE
Generator for random (but legal) MSIL code

### ISSUE THREAD

**Issue by diab0l** [dotnet/llilc#503]
Mentioned in [Areas to Contribute](https://github.com/dotnet/llilc/wiki/Areas-To-Contribute).

I'd like to contribute to LLILC, but don't really know where to start.
So this seems like the perfect place :D

**Comment by russellhadley** [comment]
I need to dig into the assignment thing @diab0l.  Chalk it up to my github ignorance.  :)

**Comment by russellhadley** [comment]
This issue has been picked up by the community, please talk to @diab0l and @AndyAyersMS if you'd like to help out.   @AndyAyersMS is the maintainer in this area so I'm making him the assignee.
