### ISSUE TITLE
Investigate LLILC Generics\Exceptions test case failures

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#513]
12 Generics\Exceptions test cases were added to CoreCLR in https://github.com/dotnet/coreclr/pull/839.
12 of them have failures with LLILC. Investigate the causes.

**Comment by AndyAyersMS** [comment]
As I noted in #514, I suspect all these tests require the ability to catch an exception. We're not quite ready for this yet so that's why they all fail. But it would be a good thing to verify.

**Comment by AndyAyersMS** [comment]
All these are already reclassifed as EH failures, so nothing to do here.
