### ISSUE TITLE
Reader: enable vararg support

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#52]

**Comment by russellhadley** [comment]
@erozenfeld is this still open?  I'm guessing that we can close this because the underlying pinvoke issue is closed.

**Comment by erozenfeld** [comment]
@jkotas Can you please confirm that CoreCLR doesn't support CORINFO_CALLCONV_VARARG calling convention?

**Comment by jkotas** [comment]
Managed varargs are not supported in .NET Core profile. System.ArgIterator and related types that are required to use managed varargs are not part of .NET Core profile.

CoreCLR includes code to support varargs, but it is there just for the legacy scenarios. We are not doing work to make it work cross-platform, etc.
