### ISSUE TITLE
Code page needs to be changed to properly run individual tests

### ISSUE THREAD

**Issue by Bevinsky** [dotnet/llilc#527]
In order to run coreclr test cases with LLILC, CMD needs to be on code page 65001 or the jit throws a NotSupportedException. #12 has more information about this.

LLILCTestEnv.cmd is provided in the tests directory with the necessary commands to set up a cmd session for running LLILC with corerun, but it doesn't set the code page (`chcp 65001`). This should probably be added to the file.

**Comment by AndyAyersMS** [comment]
According to @ellismg this is fixed in more recent System.Console builds but our config files for the tests are pulling in an older version. Once we know how to update to something more recent I'll do the work over in CoreCLR and verify we no longer need this for simple testing.
