### ISSUE TITLE
Amend wiki with information on how to run individual tests manually

### ISSUE THREAD

**Issue by Bevinsky** [dotnet/llilc#528]
The wiki's [Testing](https://github.com/dotnet/llilc/wiki/Testing) section contains instructions on how to run the CoreCLR tests for LLILC via a test harness. However, there is no information on how to bypass the harness and run individual tests.

The process I've identified for running the test cases on Windows in cmd is:
* Copy the LLILCJit.dll in `llvm-build/bin/Debug` to the CoreCLR binary directory (`coreclr/bin/Product/<build>/`)
* Run the `llilc/test/LLILCTestEnv.cmd` to set the needed env variables. If debug printing is desired, also run `set COMPlus_DumpLLVMIR=[summary, verbose]`.
* Set the code page to 65001 (See #527 and #12).
* Run the test binary via CoreRun as normal.

(Also as an aside, I don't think the Testing page is in the wiki sidebar.)

**Comment by erozenfeld** [comment]
I updated the Testing section with this information.
