### ISSUE TITLE
Phi nodes do not get an operand for every predecessor

### ISSUE THREAD

**Issue by Bevinsky** [dotnet/llilc#529]
While investigating #489, I found that LLILC is seemingly constructing phi nodes incorrectly.

`maintainOperandStack` will ensure that phi nodes are added for any values that spill over into successor blocks. However, phi nodes require an operand for each predecessor of the node's block. If the block has a predecessor that is not reachable, `maintainOperandStack` will never be called on it, and the required phi node operand will never be added.

This is normally not a problem, as LLILC's own dead block removal would remove the offending blocks and everything would then match up. However, `llvm::removeUnreachableBlocks` is failing because of this, as it expects phi nodes to have an operand for every predecessor.

I suggest that when adding phi nodes, all operands are added at once, but with undef values. Then, as the real operands are processed the undef's are replaced with the correct values. Once IR translation is over, `removeUnreachableBlocks` is called and removes the unreachable blocks (and their associated undef phi node operands).

I've implemented this change in my branch (b1ff12fe8357f941f99eb6de4f8a0f78124ec91d). It's not yet ready for a PR (I haven't run all tests, and I'm not sure what to do with the old block removal code), but PTAL.

**Comment by erozenfeld** [comment]
The changes look good to me, thanks for working on this. I just left a few minor comments. In msilToIR right after calling fgRemoveUnusedBlocks I would add a pass (under #if !defined(NODEBUG)) checking that fgNodeIsVisited is true on all surviving blocks.

**Comment by Bevinsky** [comment]
Thanks for the comments. I'll amend the code accordingly.

One thing though; should I verify that the visited bit is set on all remaining blocks and then clear it? This is what the current implementation does, though I'm not entirely sure why.

**Comment by AndyAyersMS** [comment]
Fixed by #533.
