### ISSUE TITLE
Implement GenIR::getValueFromRuntimeHandle

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#532]

**Comment by pgavlin** [comment]
Other JITs either
a) do not optimize this path, or
b) only optimize here if the incoming argument is the result of lowering a ldtoken instruction.

We don't yet have the ability do detect (b), so we're currently stuck with (a).

I've opened #551 to track improving this.

**Comment by AndyAyersMS** [comment]
Roslyn is unblocked with #550, so closing this.
