### ISSUE TITLE
CI gets confused when tests that used to fail get enabled

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#541]
Our build status has been red recently on windows because the baseline jit (which doesn't have fixes, evidently) is unable to handle some new tests:

```
00:42:10.100 There were failures with the baseline Jit
00:42:10.100 At C:\Users\TEMP\AppData\Local\Temp\2\hudson3022659791935578322.ps1:15 char:1
00:42:10.100 + throw "There were failures with the baseline Jit"
00:42:10.100 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
00:42:10.101     + CategoryInfo          : OperationStopped: (There were fail...he baseline
```

Seems unfortunate this is reported as a build failure.

How does the baseline jit get updated?

**Comment by AndyAyersMS** [comment]
This is still happening. Our [official CI runs](http://dotnet-ci.cloudapp.net/job/dotnet_llilc_release_win64/) still show failures on windows from the baseline jit. I suspect it is just old and maybe the idea was the baseline jit would get updated when the tests were green, but because of this particular failure mode the update never fires. 

@richardlford can you take a look?

**Comment by richardlford** [comment]
I’ll take a look today.

**Comment by AndyAyersMS** [comment]
@richardlford any update on this?

**Comment by richardlford** [comment]
@AndyAyersMS, no update yet. I hope to get to this later today.

**Comment by richardlford** [comment]
@AndyAyersMS, I think this was fixed by @pgavlin  when we switched to python evaluation scripts. It now uses the correct logic.
