### ISSUE TITLE
Track last-known-good commits of repos LLILC depends on

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/llilc#543]
It would be good to know what sync points of LLVM and CoreCLR are known/expected to work with a given LLILC commit, to avoid getting randomized by failures from accidental mismatched sync (and to avoid halting all progress when a change requiring LLILC update gets checked in to CoreCLR).

Strawman proposal:
1. Add a file to LLILC repo whose contents look something like
   
   > llvm: 16afeda234
   > coreclr: 3251342a
2. Lab scripts checkout the specified commits of each repo before building and running tests
3. When LLVM or CoreCLR has a change that breaks LLILC, when the fix goes in to LLILC, that change also includes updating the LKG for the relevant repo
4. We're already pulling changes from LLVM:master to LLVM:MS on a regular basis.  Whenever LLVM:MS gets updated in this way, LLILC would need a companion change updating the LKG stamp for LLVM
5. Branch owner (or a bot?) would daily test updating CoreCLR LKG to latest and check in the change to update if successful.  (And if unsuccessful, we could file an issue and fix it in parallel to ongoing work without bringing down LLILC testing in the meantime)
6. When we can start using packages/drops instead of building LLVM/CoreCLR, step 2 would change accordingly, but the rest of this should be pretty much the same.

I'm curious if others agree that something like this would be a good idea.

**Comment by erozenfeld** [comment]
Yes, this is definitely a good idea. We should always know lkg timestamps for llvm and coreclr.

**Comment by apskim** [comment]
Have you considered using `git subtree`, relying on a fixed commit of llvm/coreclr, and only update the subtrees occasionally to other fixed commits that have been tested to work?

**Comment by JosephTremoulet** [comment]
@apskim, would that require housing the llvm and coreclr enlistments as subfolders inside the llilc enlistment?  I'm hesitant to start requiring that (currently we're flexible wrt how a dev wants to arrange these locally in relation to each other, and in fact putting llvm under llilc would be inverted from the setup that many of us use where llilc is homed under llvm/tools).  Also, where we'd really like to end up is being able to pull down prebuilt packages of llvm and coreclr instead of building them locally, and it seems like even if we used subtree now we'd have to switch to something like I outlined above once we get to packages, no?

**Comment by JosephTremoulet** [comment]
@adiaaida, would this be easy to set up in the lab?

**Comment by adiaaida** [comment]
I believe we could do this. Right now we are running a saved LKG LLILC against a new CoreCLR, but we could definitely also save a text file that saves the hashes of CoreCLR for what's being checked in to use against the LKG LLILC and pull that CoreCLR to use with LLILC and a new CoreCLR to use against the current LLILC.

**Comment by JosephTremoulet** [comment]
Sorry, why is there an "LKG" LLILC and a "current" LLILC?  I was thinking about PR jobs; can they simply sync their coreclr and llvm enlistments to a commit that's specified in a file checked in to the LLILC repo?  Then daily we'd want to test updating to latest llvm/coreclr, which presumably could be a PR job with that file changed to specify the latest commits.  And if we have a job that runs every day to compare today's LLILC against yesterday's LLILC to check for regressions, I'd hope that in each case it could use the coreclr/llvm sync points specified in the file corresponding to each LLILC.
