### ISSUE TITLE
Run test cases using complus_expandallonload

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#556]
We've been looking for ways to force the JIT to generate code for more of the methods in an assembly. If you set complus_expandallonload=1, the CoreCLR will instruct the JIT to generate code for all methods in an assembly when the assembly is loaded.

I've started using this to work my way through mscorlib with a simple test case.

**Comment by AndyAyersMS** [comment]
Have simple test cases running end to end now, and have opened relevant issues. 

I'll leave this open as I intend to run a broader set of cases this way.

**Comment by russellhadley** [comment]
@AndyAyersMS Is this something that we can call done?

**Comment by AndyAyersMS** [comment]
I think we can. I hit some strange failures (both with LLILC and with RyuJit) when running things more broadly and I'm not sure it is worth tracking them down. Our time is probably better spent bringing up NGEN or RtR which will give us similar coverage.
