### ISSUE TITLE
Type conversion failure in binary op

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#558]
In `System.Diagnostics.Tracing.DataCollector.ScalarsEnd`, we see:
```
  .locals init (valuetype System.Diagnostics.Tracing.EventSource/EventData* V_0)
  ...
  IL_0016:  ldloc.0
  IL_0017:  ldfld      int64 System.Diagnostics.Tracing.EventSource/EventData::m_Ptr
  IL_001c:  conv.ovf.u
  IL_001d:  sub
  IL_001e:  ldc.i4.1
  IL_001f:  div
```
we type the result of the `sub` as a pointer, and can't handle this when we hit the `div`.

**Comment by AndyAyersMS** [comment]
Here's another similar case. In `System.Text.EncoderFallbackBuffer.InternalFallback` we see
```
  IL_0017:  ldarg.2
  IL_0018:  ldind.i
  IL_0019:  ldarg.0
  IL_001a:  ldfld      char* System.Text.EncoderFallbackBuffer::charStart
  IL_001f:  sub
```
where arg2 is `char*& chars`. The `ldind.i` gives us an int, and we fail to handle this in the `sub`.

**Comment by JosephTremoulet** [comment]
Per [ECMA](http://www.ecma-international.org/publications/standards/Ecma-335.htm), the acceptable input type combinations and resultant output types for these binary arithmetic operations are described in Table III.2, but
 > the type referred to here is the type as tracked by the CLI rather than the more detailed types used by tools such as CIL verification. The types tracked by the CLI are: int32, int64, native int, F, O, and &"

(section I.12.1 has more detail on the different type systems).  So from the CLI-types perspective, those pointers were 'native int' once they were pushed on the stack.  Seems we could either aggressively type unmanaged pointers as 'native int' in `convertToStackType` or (preferably?) add some bail-out code in the arithmetic instruction processing that retypes pointer inputs as 'native int' when it sees a nonsensical mix of pointers and ints in the input.
