### ISSUE TITLE
Missing sign/zero extension or perhaps bad IL

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#559]
In `System.IO.Directory.InternalCreateDirectory` we see
```
  int32 V_8,
  native int V_21,
  ...
  IL_00fe:  ldloc.s    V_8
  IL_0100:  dup
  IL_0101:  stloc.s    V_21
```
and get confused at the `stloc.s` in `convertFromStackType` because we have an i32 operand on the stack and want an i64, and don't expect to perform a lengthening convert there.

Not sure offhand if we should just do the extension here (sign? zero?) or if the IL is invalid.

**Comment by JosephTremoulet** [comment]
[ECMA-335](http://www.ecma-international.org/publications/standards/Ecma-335.htm) III.3.63 (stloc) says "the type of *value* shall match the type of the local variable as specified in the current method’s locals signature" in the "Description" section, but doesn't repeat it under "Correctness" (and goes on to say to say "verification also checks that the type of value is verifier-assignable-to the type of the local, as specified in the current method’s locals signature" under "Verifiability"), for what that's worth.

**Comment by AndyAyersMS** [comment]
Under I.8.7.3, we see "A location type T is assignable-to a location type U if one of the following holds: ...4. T has intermediate type native int and U has intermediate type int32, or vice-versa."

So I'd be tempted to say the IL is ok and we need to support a lengthening convert when popping an int32 from the stack when we expect to get a native int. But what kind of extension...?

**Comment by JosephTremoulet** [comment]
Presumably we can figure out which type of extension RyuJit uses and follow suit.

**Comment by JosephTremoulet** [comment]
Come to think of it, the situation is similar when a binary arithmetic op gets one `int32` input and one `native int` input on a 64-bit target.  Table III.2 says the result type is `native int`, but I don't see anywhere specifying whether to sign- or zero-extend.  LLILC currently zero extends for the .ovf.un variants and sign extends for the rest; it would probably behoove us to match whatever RyuJit does.

**Comment by AndyAyersMS** [comment]
From what I can tell in the code, it's a sign extension. I'll work up some simple test cases and look at the actual codegen.

**Comment by erozenfeld** [comment]
I think we can use table III.8 here. It says "Sign extend" for conversions from int32 to native int.
