### ISSUE TITLE
Reader: generate debug info metadata

### ISSUE THREAD

**Issue by xen2** [dotnet/llilc#565]
Generating proper debug info (http://llvm.org/docs/SourceLevelDebugging.html) would enable a large array of existing debugging tools (i.e. GDB/LLDB) to work as is for:
- Proper (non-mangled) function names and stack traces
- Source level debugging (can step in C# code and disassembly with interleaved C# to easily know what MSIL/C# generates what assembly code) => also good for profiling
- Threads, breakpoints, conditional breakpoints
- Expression evaluations
- Local/Global variables
- Structures/Classes
- Strings, Arrays
- Debugging codegen bugs/side-effects would become much more easy

This would work right away on almost every platforms (incl. AOT), resistant to optimizations and very low runtime cost (mostly metadata).

Of course a few managed-specific stuff wouldn't work right away (could be added later) but the initial support would allow to more easily understand generated assembly code and fix issues.

Also, mixed-debugging (native+managed) on Linux platforms would be made easy (not sure if the better managed debugging approach would permit that easily?).

Note: didn't investigate yet, but http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-January/081419.html might mean there might be other approaches (still, I suppose it will still need to use DIBuilder to do source-level debugging, to at least map from assembly loc + variables loc to MSIL).

Does it make sense for LLILC?

**Comment by russellhadley** [comment]
I'm still thinking about how this might fit in our bring up.  We're going to check in support (soon) for producing the debug format consumed by CoreCLR, and there is a lldb plugin for use with windbg to allow for some access to the managed frames/garbage collector.  But what you're proposing would cover more than that (right?)  It's mostly just about adding the complete source info as well.  I'm not sure at this point what the best way to extract the line info for the MSIL is but I think for the long term this is the right way to go.  One wrinkle we'll have is that today we're reusing the line field for the MSIL offset for a method.  If we're going to support both the CoreCLR mediated debugging as well as existing debugging tools the debug metadata in LLVM will need to be extended to carry the extra payload.  What's the next step here @xen2?
