### ISSUE TITLE
MIPS support

### ISSUE THREAD

**Issue by jasonwilliams200OK** [dotnet/llilc#578]
Alongside ARM, LLVM toolchain [supports MIPS](http://llvm.org/reports/coverage/lib/Target/Mips/index.html) as well ([once used to be Microsoft's bread and butter](https://msdn.microsoft.com/en-us/library/gg156127(v=winembedded.70).aspx), then Windows 10 for everything (but MIPS) happened), it will be somewhat unfair if MIPS is left behind in dotnet paradigm.

Please consider adding support for MIPS instruction set, transpiling MSIL to MIPS via LLVM as well as CL. There must be gigantic amount of legacy code in VC compiler for MIPS assembly, which could be resurrected, in pursuit of retaining the legacy. You guys also stand a better chance convincing the bosses and bosses-like entities in VC team to keep MIPS assembler/linker alive. :)

It seems like there are few instances of MIPS instruction set in CoreCLR: https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=mips. Not sure how complete is the support.

Related: https://github.com/dotnet/coreclr/issues/969.

**Comment by AndyAyersMS** [comment]
Part of the reason we're using LLVM for LLILC and working entirely in the open here on GitHub alongside the CoreCLR and partner teams is to facilitate this kind of porting flexibility.

As others have pointed out, the door is open for interested parties to step up and make all this work on MIPS. You don't have to persuade Microsoft to do anything...

**Comment by jimhogg** [comment]
Not seen any more discussion here, so closing this issue.
