### ISSUE TITLE
Set up some simple performance benchmarks

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#590]
We need to start looking at the performance of the jit and the performance of the code it creates. First step is to create or adapt some simple benchmarks to run against CoreCLR and get them set up as CoreCLR tests.

**Comment by russellhadley** [comment]
@adiaaida,  your work to do the benchstones was against the desktop.  What would it take to move those to coreclr so they can be run in Jenkins?

**Comment by adiaaida** [comment]
It shouldn't take too much. I will test out one to see how easy it is to move them over and get back to you.
