### ISSUE TITLE
Debugger: Debug info for locals

### ISSUE THREAD

**Issue by adiaaida** [dotnet/llilc#593]
Add debug info support for locals

**Comment by russellhadley** [comment]
@adiaaida Move this out to S87 and add any notes.

**Comment by russellhadley** [comment]
@adiaaida can you add some notes on where we're at with this?

**Comment by adiaaida** [comment]
* Have added logic in LLILC reader to create dbg.declare intrinsics for locals.
* declare intrinsics are currently being dropped in LLVM. tracking down where this is happening and why/what happens with clang.

**Comment by adiaaida** [comment]
* Added logic to LLILCJit to extract locals info from the dwarf debug info
* Added logic to pass debug info to CLR EE.
* Opened in debugger and we are seeing accurate locals info.

* Discovered that stepping is broken. It appears this is unrelated to the locals support. I am opening an issue.

**Comment by russellhadley** [comment]
@adiaaida this will be held in S87.  I'd like to get this in as soon as we can.

**Comment by adiaaida** [comment]
We currently cannot run with my changes with zap disabled. Need to investigate.
