### ISSUE TITLE
Investigate Regression\VS_is64_JIT test failures

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#601]
CoreCLR PR https://github.com/dotnet/coreclr/pull/1059 added Regression\VS_is64_JIT tests. Some of the tests cannot run with LLILC. Investigate the causes. Failure list include:

V1.2-M02\b26496\_1d6bgof.cs
V2.0-Beta2\b309539\_ba6c0ou.cs
M00\b111130\makework.cs
V2.0-RTM\b539509\b539509.cs
V2.0-Beta2\b302558\_aopst1l.cs
V2.0-Beta2\b311420\b311420.cs
M00\b99219\b99219.cs
M00\b141358\test.cs
M00\b115253\hello2.cs
V1.2-M02\b102886\ovf.cs
V1.2-M02\b10828\redundant.cs

**Comment by AndyAyersMS** [comment]
I'll triage these....

**Comment by AndyAyersMS** [comment]
V2.0-Beta2\b311420\b311420.cs now passes. All the rest require EH.
