### ISSUE TITLE
Investigate Regression\CLR-x86-EJIT test case that has issue with LLILC

### ISSUE THREAD

**Issue by libengu** [dotnet/llilc#616]
Core CLR PR https://github.com/dotnet/coreclr/pull/1088 added multiple test directories under Regression. Three of the test cases failed if run with LLILC. Investigate the causes.

JIT\Regression\CLR-x86-EJIT\V1-M11-Beta1\b40138\b40138
JIT\Regression\CLR-x86-EJIT\V1-M11-Beta1\b45679\b45679
JIT\Regression\CLR-x86-EJIT\V1-M12-Beta2\b46847\b46847

**Comment by AndyAyersMS** [comment]
Will reassess these.

**Comment by AndyAyersMS** [comment]
```
JIT\Regression\CLR-x86-EJIT\V1-M11-Beta1\b40138\b40138.cmd -- EH
JIT\Regression\CLR-x86-EJIT\V1-M11-Beta1\b45679\b45679.cmd -- EH
JIT\Regression\CLR-x86-EJIT\V1-M12-Beta2\b46847\b46847.cmd -- EH
```
