### ISSUE TITLE
LLVM Build fails with stdint.h error

### ISSUE THREAD

**Issue by krk** [dotnet/llilc#619]
Building the llvm project fails with the error `llvm-build\include\llvm/Support/DataTypes.h(47): fatal error C1189: #error :  "Compiler must provide an implementation of stdint.h"` which is reported for every inclusion of `DataTypes.h`

**Comment by pgavlin** [comment]
It looks like you're building on Windows--is this correct? If so, which version of Visual Studio do you have installed?

**Comment by krk** [comment]
I am building on Windows 8.1 and have VS2013 Update 4 and VS2015 RC installed, using the "Visual Studio 12 2013 Win64" cmake generator.

**Comment by krk** [comment]
Figured I have ran cmake-gui configure once without the WITH_CORECLR parameter, subsequent console cmake runs couldn't find stdint.h file. It has found the stdint.h file after cleaning the llvm-build directory.

**Comment by pgavlin** [comment]
Ah, got it. Yeah, this is an unfortunate side-effect of the CMake cache. Glad you were able to figure things out :)
