### ISSUE TITLE
LLVM to MSIL

### ISSUE THREAD

**Issue by sirinath** [dotnet/llilc#626]
With a view for better cross language support for libraries compiled into LLVM IR it could be a good option to support LLVM to MSIL compilation.

Hence you should be easily use any LLVM based languages without a FFI.

**Comment by jimhogg** [comment]
Interesting idea.  LLVM is a lower-level of intermediate rep. than MSIL.  So, such a tool would consume chunks of LLVM bitcode, and infer that they form a low-level representation of some particular MSIL instruction.  You would also need to infer the corresponding MSIL metadata.  This would make an interesting (and challenging) project (but not one that we are working on)

**Comment by jimhogg** [comment]
No further replies, so closing . . .

**Comment by sirinath** [comment]
This might be a more generic way to support many languages generating .net code.

**Comment by enginekit** [comment]
Hello @sirinath.

What is your progression on this?

---

Did you see ...
**LLVM-to-MSIL**  https://github.com/soywiz/llvm-to-msil

---
Or 

LLVM => web-assembly => MSIL


similar to this https://github.com/soywiz/wasm2kt, LLVM=>web-asm=> Kotlin

web-asm=> dotnet , see  https://github.com/RyanLamansky/dotnet-webassembly

---
