### ISSUE TITLE
2 way interface AOT and JIT compilation for LLVM languages

### ISSUE THREAD

**Issue by sirinath** [dotnet/llilc#627]
There are great LLVM languages like Clang, Julia, Rust, Swift, Objective C, etc.

It will be good to create language specific packages to be directly consumed within these languages from existing .net code. Also convert packages in these languages to be directly consumed in .net.

**Comment by jimhogg** [comment]
For LLILC, we will want to be able to Pinvoke code (from C#) that's already been compiled down to native, and vice versa.  So you can think of that as partly addressing the Clang/C/C++ part above.  So that's the current focus.

**Comment by jimhogg** [comment]
No further replies, so closing . . .
