### ISSUE TITLE
Assert when Roslyn compiled by LLILC compiles Roslyn with /parallel+.

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#631]
This is part of #629. @erozenfeld did the initial investigation. From his email:

> I was able to set up a Roslyn build, then extracted csc command for
> building Microsoft.CodeAnalysis.CSharp.dll (biggest Roslyn
> assembly). I ran into a couple of asserts related to type translation
> and checked in fixes for them. Roslyn csc.exe has /parallel[+|-]
> flag. 
> . . .
> 
> With /parallel+ there is something else going on. Sometimes
> compilation succeeds, sometimes it hangs, and sometimes we get an AV
> in gc like the one below. It doesn't take long to repro this AV.
> 
> Assert failure(PID 21304 [0x00005338], Thread: 15628 [0x3d0c]):
> Consistency check failed: AV in clr at this callstack:
> 
> ------
> CORECLR! GCToEEInterface::ScanStackRoots + 0x1B4 (0x00007ffe`8cc8f6c0)
> CORECLR! CNameSpace::GcScanRoots + 0x1D6 (0x00007ffe`8cc60852)
> CORECLR! WKS::gc_heap::mark_phase + 0x463 (0x00007ffe`8cd7225b)
> CORECLR! WKS::gc_heap::gc1 + 0x1FB (0x00007ffe`8cd647c7)
> CORECLR! WKS::gc_heap::garbage_collect + 0xAC7 (0x00007ffe`8cd6456f)
> CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x54B (0x00007ffe`8cd3aa7b)
> CORECLR! WKS::gc_heap::try_allocate_more_space + 0x3EE (0x00007ffe`8cd8d802)
> CORECLR! WKS::gc_heap::allocate_more_space + 0x27 (0x00007ffe`8cd45237)
> CORECLR! WKS::GCHeap::Alloc + 0x211 (0x00007ffe`8cd39215)
> CORECLR! Alloc + 0x1A9 (0x00007ffe`8cb21f51)
> CORECLR! AllocateArrayEx + 0x87C (0x00007ffe`8cb229d8)
> CORECLR! JIT_NewArr1 + 0x578 (0x00007ffe`8c95e774)
> <no module>! <no symbol> + 0x0 (0x00007ffe`2e01aaeb)
> <no module>! <no symbol> + 0x0 (0x00007ffe`2e4d9872)
> <no module>! <no symbol> + 0x0 (0x00000000`00000020)
> CORECLR! JIT_Ldelema_Ref + 0x12F (0x00007ffe`8c959743)
> CORECLR! JIT_Ldelema_Ref + 0x12F (0x00007ffe`8c959743)

This task is to diagnose and fix the problem causing the assertion.

**Comment by richardlford** [comment]
I've been able to reproduce this, except I got an access violation instead.

**Comment by richardlford** [comment]
I've diagnosed the reason for the AV. The code in the CLR that handles
conservative garbage collection is scanning the stack for a thread like this:

In file d:\bm\dr2\coreclr\src\vm\gcenv.cpp

```
VOID GCToEEInterface::ScanStackRoots(Thread * pThread, promote_func* fn, ScanContext* sc)
{
    GCCONTEXT   gcctx;

    gcctx.f  = fn;
    gcctx.sc = sc;
    gcctx.cf = NULL;

    ENABLE_FORBID_GC_LOADER_USE_IN_THIS_SCOPE();

    // Either we are in a concurrent situation (in which case the thread is unknown to
    // us), or we are performing a synchronous GC and we are the GC thread, holding
    // the threadstore lock.

    _ASSERTE(dbgOnly_IsSpecialEEThread() ||
                GetThread() == NULL ||
                // this is for background GC threads which always call this when EE is suspended.
                IsGCSpecialThread() || 
                (GetThread() == ThreadSuspend::GetSuspensionThread() && ThreadStore::HoldingThreadStore()));

    pThread->SetHasPromotedBytes();

#ifdef FEATURE_CONSERVATIVE_GC
    if (g_pConfig->GetGCConservative())
    {
        // Conservative stack root reporting
        // We will treat everything on stack as a pinned interior GC pointer
        // Since we report every thing as pinned, we don't need to run following code for relocation phase.
        if (sc->promotion)
        {
            Object ** topStack = (Object **)pThread->GetFrame();
            Object ** bottomStack = (Object **) pThread->GetCachedStackBase();
            Object ** walk;
            for (walk = topStack; walk < bottomStack; walk ++)
            {
                if (((void*)*walk > (void*)bottomStack || (void*)*walk < (void*)topStack) &&
                    ((void*)*walk >= (void*)g_lowest_address && (void*)*walk <= (void*)g_highest_address)
                    ) <<<<<<< pc is here, line 521
                {
                    //DbgPrintf("promote " FMT_ADDR " : " FMT_ADDR "\n", walk, *walk);
                    fn(walk, sc, GC_CALL_INTERIOR|GC_CALL_PINNED);
                }
            }
        }


+		bottomStack	0x000000ec49850000 {???}	Object * *
+		topStack	0x000000ec4984d05c {0x00007ffbf5fd2370 
       {coreclr.dll!const InlinedCallFrame::`vftable'} {m_pMethTab=0x00007ffbf5ad8a1c {coreclr.dll!StubCacheBase::AddStub(const unsigned char *, Stub *)} {...} }}	Object * *

+		g_highest_address	0x000000ec286b0000 <Error reading characters of string.>	unsigned char *
+		g_lowest_address	0x000000ec106b0000 "\x10†3\x1bì"	unsigned char *

        // Also ask the explicit Frames to report any references they might know about.
        // Generally these will be a subset of the objects reported below but there's
        // nothing that guarantees that and in the specific case of a GC protect frame the
        // references it protects may live at a lower address than the frame itself (and
        // thus escape the stack range we scanned above).
        Frame *pFrame = pThread->GetFrame();
        while (pFrame != FRAME_TOP)
        {
            pFrame->GcScanRoots(fn, sc);
            pFrame = pFrame->PtrNextFrame();
        }
    }
    else
#endif
```

Stack stack is walked in pointer-sized steps. The problem is that
topStack is not pointer-sized (i.e. 8 byte) aligned, since its value
is 0x000000ec4984d05c. So then when walk == bottomStack - 4
the *walk tries to read 8 bytes the last 4 of which are beyond the
bounds of the stack, thus causing an AV. 

It seems that another bad effect is that any pointers on the stack,
which presumable are 8-byte aligned, are not actually read
as the stack is being scanned skewed by 4 bytes.

So, it seems that this code would be more robust if it made
sure the stack scan started at an aligned address. 

On the other hand, I believe the Windows X64 ABI requires the
stack to be 8 (or possibly 16) byte aligned, so it is
suspicious that the stack top is not aligned.

**Comment by russellhadley** [comment]
@richardlford I want to hold this in S86.  Let's make sure this gets done for sprint shut down.

**Comment by richardlford** [comment]
There no longer is a problem with parallel+ so closing. Roslyn has bootstrapped multiple times in parallel mode.
