### ISSUE TITLE
Assert while importing indirect calls through function-pointer-typed locals/args

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#633]
`Assertion failed: Target->getType()->isIntegerTy(Reader.TargetPointerSizeInBits), file ..\..\..\..\..\tools\llilc\lib\Reader\abisignature.cpp, line 314`

The EE does not distinguish between normal pointers and function pointers, so the reader ends up blowing up when it tries to call through what looks like a pointer to a struct.

**Comment by richardlford** [comment]
Closed by PR 805,
