### ISSUE TITLE
Assertion failure due to a type mismatch between a storage location and the value being stored

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#634]
`Assertion failed: getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!", file ..\..\..\lib\IR\Instructions.cpp, line 1038`

**Comment by richardlford** [comment]
Of the 10 (formerly) failing tests, 2 no longer exist and the remaining 8 all pass.
