### ISSUE TITLE
Assertion in LLVM due to overlarge relocation

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#639]
This pops up during a number of the new IL tests.

`Assertion failed: ((int64_t)Result <= INT32_MAX) && "Relocation overflow", file e:\dev\llvm\lib\executionengine\runtimedyld\Targets/RuntimeDyldCOFFX86_64.h, line 82`

**Comment by AndyAyersMS** [comment]
We shouldn't be generating relative relocations so this is likely an issue with LLVM lowering.

**Comment by pgavlin** [comment]
Closed by #654.
