### ISSUE TITLE
Assertion: stack values smaller than a native int cannot be coerced to pointers

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#640]
This pops up during one of the new IL tests.

`Assertion failed: !NeedsReinterpret && "cannot reinterpret and extend", file ..\..\..\..\..\tools\llilc\lib\Reader\readerir.cpp, line 2088`

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
Here we have 
```
	call int32 a::byrefsubbyref(class ctest&, class ctest&)
	newobj     instance void ctest::.ctor()
	stloc.0
	ldloca V_1
	call int32 a::byrefsubbyref(class ctest&, class ctest&)
```

So an `int32` is being passed as a `ctest&`. I actually wonder if this is a typo and the second call was supposed to target `a::i4subbyref(int32, class ctest&)`. It seems painful to have to keep allowing `int32` to masquerade as a pointer type.
