### ISSUE TITLE
Assertion: bad value passed to mkrefany

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#641]
This pops up during one of the new IL tests.

`Assertion failed: isManagedPointerType(Object->getType()) && "wrong type for refany value", file ..\..\..\..\..\tools\llilc\lib\Reader\readerir.cpp, line 6712`

**Comment by AndyAyersMS** [comment]
Will investigate.

**Comment by AndyAyersMS** [comment]
We evidently need to tolerate seeing arbitrary integers passed as the values for `mkrefany`, despite Ecma-335 III.4.19 requiring either `&` or `native int`. Here the IL in question is:
```
call int32 f()
mkrefany int32
```
