### ISSUE TITLE
Assertion: unexpected CorInfoType passed to GenIR::size

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#643]
This pops up in one of the new IL tests.

`Assertion failed: (0) && "UNREACHED", file ..\..\..\..\..\tools\llilc\lib\Reader\readerir.cpp, line 1957`

**Comment by AndyAyersMS** [comment]
Will take a look.

**Comment by AndyAyersMS** [comment]
Issue is that we have some dodgy IL feeding a box:
```
  IL_0006:  ldind.u1
  IL_0007:  box        mynamespace.e_t
```
where the box type is a value class that is two uint8 fields.

We can fix this case by passing the size of the box type to `GenIR::convertToBoxHelperArgumentType` instead of trying to deduce the size from the `CorInfoType`.
