### ISSUE TITLE
Can LLILC replace Xamarin in the future?

### ISSUE THREAD

**Issue by ygc369** [dotnet/llilc#653]
I hope so. Xamarin is too expensive.

**Comment by jimhogg** [comment]
Xamarin is a large product – everything from Virtual Machine, thru compiler/JIT, extensive libraries, Forms Package to IDEs.  LLILC, in comparison, provides just one step on the developer-to-App path: the step that converts MSIL into native code.  So we're not comparing apples with apples.  (Perhaps I've not understood the question?)

**Comment by jimhogg** [comment]
No further replies, so closing . . .
