### ISSUE TITLE
NGEN: investigate if anything special needs to be done for unwind info allocation

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#657]
From legacy jit:

// For prejitted code we split up the unwinding information into
// separate sections .rdata and .pdata

Check if need to do anything here.

**Comment by russellhadley** [comment]
@erozenfeld is this complete?

**Comment by erozenfeld** [comment]
Yes, the comment in the legacy jit might be out-of-date. The code there doesn't do anything special for unwind info allocation for ngen.
