### ISSUE TITLE
NGEN: GS cookie constant needs to be accessed through an indirection

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#658]
2.5 GS cookie constant needs to be accessed through an indirection. From RyuJit:
if (compiler->gsGlobalSecurityCookieAddr == nullptr)
    {
        // load the GS cookie constant into a reg 
        //
        genSetRegToIcon(regGSConst, compiler->gsGlobalSecurityCookieVal, TYP_I_IMPL);
    }
    else
    {
        // Ngen case - GS cookie constant needs to be accessed through an indirection.
        instGen_Set_Reg_To_Imm(EA_HANDLE_CNS_RELOC, regGSConst, (ssize_t)compiler->gsGlobalSecurityCookieAddr);
        getEmitter()->emitIns_R_AR(ins_Load(TYP_I_IMPL), EA_PTRSIZE, regGSConst, regGSConst, 0);
    }

**Comment by russellhadley** [comment]
Pull out of milestone to reschedule
