### ISSUE TITLE
Start early work on WebAssembly compilation target

### ISSUE THREAD

**Issue by dsaf** [dotnet/llilc#663]
I know it is still in early stage, but could you please make sure that *direct* C# compilation is supported as soon as possible? It would be beneficial if Roslyn team could also feed their requirements into the design group very early. I am sure Google will be vocal about Go and Dart.

https://github.com/WebAssembly/design/blob/master/FAQ.md#is-webassembly-only-for-cc-programmers

https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#gcdom-integration

> Beyond the MVP, another high-level goal is to improve support for languages other than C/C++. This includes allowing WebAssembly code to allocate and access garbage-collected (JS, DOM, Web API) objects. Even before GC support is added to WebAssembly, it is possible to compile a language's VM to WebAssembly (assuming it's written in portable C/C++) and this has already been demonstrated (1, 2, 3). However, "compile the VM" strategies increase the size of distributed code, lose browser devtools integration, can have cross-language cycle-collection problems and miss optimizations that require integration with the browser.

It is possible that the C# language design could be affected as well:

https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#coroutines

> Coroutines will eventually be part of C++ and is already popular in other programming languages that WebAssembly will support.

**Comment by dsaf** [comment]
Migrated from https://github.com/dotnet/roslyn/issues/3575

**Comment by Suchiman** [comment]
Is there any comment on this? I see this as an emergency exit to avoid JS :smile: :dancer:.
Since microsoft is involved in the WebAssembly working group it would be nice if you guys ensure that the specification won't restrict C# / the CLR from running in the browser.

**Comment by jimhogg** [comment]
As you know, Roslyn currently translates C# into MSIL; whilst LLILC is currently focused on compiling MSIL into LLVM bitcode.  WebAssembly looks interesting, but clearly needs lots of work before gaining a firm foothold.  One key step is obviously getting all popular browsers to interpret/JIT wasm’s binary ASTs, and capitalize on the extra optimizations made possible by emitting the asm.js subset of JS.  (Until then, Polyfill will decompile to asm.js).  Yes, wasm is being worked on by some “big names” (Google, Microsoft, Mozilla, Apple).  We agree it deserves attention from all components of the toolchain.  So, LLILC will follow the progress of wasm and consider supporting in due course, as a clearer picture emerges.

**Comment by Suchiman** [comment]
And just in case this wasn't clear, i commented here because of the discussed [LLVM Backend](http://lists.cs.uiuc.edu/pipermail/llvmdev/2015-June/086881.html) which made this repository the most likely one to support web assembly :grinning:

**Comment by dsaf** [comment]
@jimhogg Thank you for responding! This issue was mostly opened to remind that there is a silent majority of Microsoft developers who prefer C#/F# to WinJS/TypeScript/Node.js or whatever is the *JS of the month :).

**Comment by dsaf** [comment]
@jimhogg

> So, LLILC will follow the progress of wasm and consider supporting in due course, as a clearer picture emerges.

Just hoping that wasm garbage collection integration will be designed with CLR in mind - it will be harder to change the *picture* later on...

**Comment by jimhogg** [comment]
@dsaf 
Each language has its own notion of garbage collection.  Eg: Java, C#, JS, asm.js/wasm.  And they may differ (eg: C# has structs, and interior pointers; its GC is generational and requires write barriers).  What matters is that the underlying LLVM bitcode is rich enough to represent these needs.  LLILC is already working on that topic for C# (more broadly, for CLR).
