### ISSUE TITLE
Windows installation error.

### ISSUE THREAD

**Issue by alxest** [dotnet/llilc#674]
I followed instructions written here. (https://github.com/dotnet/llilc/wiki/Getting-Started-For-Windows)
However, when I execute my version of this command,
~~~
cmake -G "Visual Studio 12 2013 Win64" ..\llvm -DWITH_CORECLR=<coreclr path>\bin\Product\$platform.$arch.$build>
~~~
which is
~~~
cmake -G "Visual Studio 12 2013 Win64" ..\llvm -DWITH_CORECLR=..\coreclr\bin\Product\Windows_NT.x64.Debug
~~~
(I omitted last ">", is it right? Otherwise it gives me syntax error.)
I see below messages.

~~~
C:\Users\sven\llilc_dir\llvm-build>cmake -G "Visual Studio 12 2013 Win64" ..\llv
m -DWITH_CORECLR=..\coreclr\bin\Product\Windows_NT.x64.Debug
-- Target triple: x86_64-pc-win32
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Sphinx disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Constructing LLVMBuild project information
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting AArch64
-- Targeting AMDGPU
-- Targeting ARM
-- Targeting BPF
-- Targeting CppBackend
-- Targeting Hexagon
-- Targeting Mips
-- Targeting MSP430
-- Targeting NVPTX
-- Targeting PowerPC
-- Targeting Sparc
-- Targeting SystemZ
-- Targeting X86
-- Targeting XCore
-- BugpointPasses ignored -- Loadable modules not supported on this platform.
CMake Error at tools/llilc/CMakeLists.txt:118 (message):
  Cannot find corinfo.h.  Please set WITH_CORECLR to a directory where
  CoreCLR was built or installed.


-- Configuring incomplete, errors occurred!
See also "C:/Users/sven/llilc_dir/llvm-build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/sven/llilc_dir/llvm-build/CMakeFiles/CMakeError.log".
~~~
What would be the reason?
Thank you.

**Comment by JosephTremoulet** [comment]
That's the error you would get if the CoreCLR build step failed or if the directory you specified after -DWITH_CORECLR was incorrect.  Can you verify that CoreCLR build (`build.cmd`) was successful, and that directory `..\coreclr\bin\Product\Windows_NT.x64.Debug` exists and is populated?  If yes to both, maybe try with a full path instead of a relative one?

**Comment by alxest** [comment]
@JosephTremoulet Yes, I checked the build was successful and that file actually exists. May I ask you the meaning of "populated"? Anyway, I will try again with full path.

**Comment by JosephTremoulet** [comment]
"populated" meaning it contains the build artifacts.  Here's what the directory looks like for me:
```
 Directory of C:\Source\coreclr\bin\Product\Windows_NT.x64.Debug

05/25/2015  03:48 PM    <DIR>          .
05/25/2015  03:48 PM    <DIR>          ..
04/13/2015  05:39 PM    <DIR>          .nuget
05/12/2015  11:49 AM           221,184 clretwrc.dll
05/12/2015  11:58 AM        16,789,504 coreclr.dll
05/12/2015  11:58 AM             2,004 coreclr.lib
05/12/2015  11:49 AM            41,984 CoreConsole.exe
05/12/2015  11:49 AM            50,176 CoreRun.exe
05/25/2015  04:30 PM             5,120 corerun.v12.suo
05/12/2015  11:56 AM         9,774,080 crossgen.exe
05/12/2015  11:55 AM           747,520 dbgshim.dll
05/12/2015  11:55 AM             3,432 dbgshim.lib
04/13/2015  05:32 PM            28,510 debug-pal.lib
05/12/2015  11:58 AM    <DIR>          gcinfo
05/12/2015  11:58 AM    <DIR>          inc
06/29/2015  12:10 PM        47,377,408 llilcjit-prun.dll
05/12/2015  11:54 AM         2,370,560 mscordaccore.dll
05/12/2015  11:54 AM             3,620 mscordaccore.lib
05/12/2015  11:55 AM         3,039,232 mscordbi.dll
05/12/2015  11:55 AM             2,006 mscordbi.lib
05/12/2015  11:59 AM         2,728,960 mscorlib.dll
05/12/2015  11:59 AM        18,359,296 mscorlib.ni.dll
05/12/2015  11:55 AM           354,816 mscorrc.debug.dll
05/12/2015  11:55 AM             4,096 mscorrc.dll
05/12/2015  11:59 AM    <DIR>          PDB
05/12/2015  11:56 AM         1,194,496 sos.dll
05/12/2015  11:56 AM            33,898 sos.lib
              21 File(s)    103,131,902 bytes
               6 Dir(s)  118,082,891,776 bytes free
```
In particular, the error you're seeing is (supposed to be) the result of not being able to find `~coreclr\bin\Product\Windows_NT.x64.Debug\inc\corinfo.h`.

**Comment by alxest** [comment]
@JosephTremoulet Thanks a lot. I checked it and nothing was populated, and actually the build was not successful. Sorry for the confusion. I followed the instructions but it went wrong. I will copy the error message below.

**Comment by alxest** [comment]
@JosephTremoulet Whole error log is too long to write here as a comment... It gives me 10 warnings and 508 errors. I have "blend for microsoft visual studio 2013 version 12.0.51020.0 Update 4" installed in my machine, cmake with version 3.2.3.

**Comment by JosephTremoulet** [comment]
Not sure what the issue would be.  Maybe try following [the more verbose steps in the coreclr documentation](https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md) (maybe you're running into the known issue listed there?).  What are the first few error messages?

**Comment by alxest** [comment]
@JosephTremoulet Thanks a lot. It seems coreclr build succeeds. (still working)
It seems giving more information on this documentation (https://github.com/dotnet/llilc/wiki/Getting-Started-For-Windows) would be helpful for someone like me. Can I make a pull request on it?

**Comment by JosephTremoulet** [comment]
@alxest, yes, we're happy to incorporate documentation improvements.  The wiki didn't allow PRs, but we've just moved all the documentation into the repo, so you can make a pull request on that file in its [new location](https://github.com/dotnet/llilc/blob/master/Documentation/Getting-Started-For-Windows.md).

**Comment by russellhadley** [comment]
@alxest @JosephTremoulet Did we get to the bottom of this?  Is this still an active issue?

**Comment by alxest** [comment]
@russellhadley Oh, it was solved. I will close this issue.
