### ISSUE TITLE
Type substitution and cast needed for return value from shared method

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#676]
When calling a shared method, the return type in the signature of the called method may involve
type variables. To get the effective type for the calling method a type substitution 
needs to be performed on the returned value. 

For example, a generic type ImmutableArray<T> can have a "T get_Item(int)" method
that returns an element of type T. If a caller has an ImmutableArray<char[]>, then 
get_Item should return a char[]. However when a shared version is called, the 
signature of the called method is "canon get_item(int)". So after the call the 
result needs a cast from type "canon" to type "char[]". 

We currently have some hacks that fix up return values to be the expected type
but we probably have not covered all cases, so this work is needed.

**Comment by erozenfeld** [comment]
I don't think we can do such a substitution after the call with what JIT-EE interface provides. In particular, I don't think we can figure out the target type (char[]) in your example.

**Comment by richardlford** [comment]
Move to next sprint.
