### ISSUE TITLE
GC: Set CodeLength accurately in the StackMap

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/llilc#679]
The Code-Length in CLR's GCInfo encoding is set to JitContext->HotCodeSize.
This is the size of the allocated code block, not the actual code length of the current function.
I have not seen any failures in the runtime with the larger size setting, but the Default CoreCLR JIT sets the size accurately. So, better to follow the same procedure.

**Comment by AndyAyersMS** [comment]
Was wondering when somebody was going to notice this... it should also make jitted code size measurements (eg from ETW) a bit more accurate.
