### ISSUE TITLE
Upstream LLVM changes

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#683]
Our branch of LLVM (https://github.com/microsoft/llvm/tree/MS) has a small number of changes that we still need to submit upstream:
- Allow the frame pointer to be read via read_register
- Lower GC_TRANSITION_{START,END} ISD nodes for CoreCLR
- Lower stack probes correctly for CoreCLR

**Comment by pgavlin** [comment]
The frame pointer change has been upstreamed; the others are still in progress.

**Comment by russellhadley** [comment]
@pgavlin where are we with this?  I'd be willing to move this to S88 if we could at least get the clr environment change in.

**Comment by pgavlin** [comment]
The environment change is in.
