### ISSUE TITLE
Begin investigating LLILC compile throughput.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/llilc#684]
We should get an early look at the throughput of the LLILC JIT s.t. we better understand the areas that need improvement. This will at least involve creating and profiling some throughput-oriented tests and real-world code.

**Comment by AndyAyersMS** [comment]
Using complus_altjitoptions=-time-passes gives at least some initial indication as to where problems might lie. This is per-jit-request data. There is also per-jit-request ETW data that we can tap into.

It might be interesting to take mscorlib, ngen it with both RyuJit and LLVM, and look at the ratios/outliers.
