### ISSUE TITLE
clang-format: Use latest builds in the lab

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/llilc#688]
The clang-format.exe used in the lab differs from developer builds resulting in inconsistencies.
Have a standard protocol to refresh the clang-format.exe regularly.
This process is best automated, if possible.

**Comment by adiaaida** [comment]
Updated the clang-tools-extra FI job in the lab to upload clang-format and clang-tidy to azure storage. Push job now uses these versions. Once we get kinks worked out of them, will update PR test job.
