### ISSUE TITLE
 track thread safety concerns of static field for SIMD

### ISSUE THREAD

**Issue by ANDREENKOS** [dotnet/llilc#720]
Track thread safety concerns of static CORINFO_CLASS_HANDLE declarations inside readerir.cpp.
static fields from GenIR should be removed.

**Comment by AndyAyersMS** [comment]
Why did this get closed? Isn't it still a problem?

**Comment by erozenfeld** [comment]
The static fields were deleted in #806.

**Comment by AndyAyersMS** [comment]
The static fields that held llvm types are gone, but the static fields that held class handles like `SIMDFloatHandle` are still around. I suppose these are a bit less dangerous but we probably don't want them either.
