### ISSUE TITLE
EH: Implement support for filters in reader

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/llilc#74]
Note: this is a much larger task than for the other handler types, because it requires outlining the filter function.

Part of #13.

**Comment by JosephTremoulet** [comment]
I'm working on getting filter outlining working in the EH branch in the Sprint 85 timeframe.

**Comment by JosephTremoulet** [comment]
This is checked in to the EH branch (commit 065c6188832f1793dc473ccf03427741f89cfffc).  I'm clearing the milestone label but leaving the issue open to track merging it into master (and updating it to the new EH representation)

**Comment by drbo** [comment]
Should this now be closed?  The EH branch has been merged.

**Comment by JosephTremoulet** [comment]
What got merged in with the EH branch for filters was a workaround that translates them into a catch with explicit rethrow.  The workaround is semantically incorrect because it delays the evaluation of the filter expression to the 2nd pass of expression unwinding (it's supposed to happen in the 1st pass), though I expect typical filter usage won't notice that difference.  The workaround is also undesirable from a debugging perspective, because any exception that a filter declines to handle will effectively have its stack trace truncated when it is ultimately handled (with the frames below the filter missing).  So I thought it made sense to leave this open to track implementing full filter support rather than the workaround (which likely requires expanding LLVM's ability to represent filters first; Clang can represent semantics correctly currently by outlining filter expressions, but that outlining is not a viable option for LLILC due to some constraints the runtime has on how filters are reported).

**Comment by JosephTremoulet** [comment]
Correction:  the rethrow used by the workaround does not truncate stack traces.  So really the sole issue is delaying filter expressions to the 2nd pass.  And to clarify that:  the issue is specifically regarding cases where an exception is raised inside a try protected by a finally/fault which itself is inside a try (possibly in a different call frame) protected by a filter, with no intervening catches -- the filter expression should be evaluated before the finally/finallies execute, but with the workaround will be evaluated after.
