### ISSUE TITLE
GC: Fix StackBase reporting in GcTables

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/llilc#758]
The FP/SP stack base should be reported in the header in addition to the slots representing liveness.

**Comment by swaroop-sridhar** [comment]
Testing a fix.

**Comment by swaroop-sridhar** [comment]
Fix is in swaroop-sridhar\FP

**Comment by russellhadley** [comment]
@swaroop-sridhar is this complete?

**Comment by swaroop-sridhar** [comment]
Here's the fix, will send out a PR now.
https://github.com/dotnet/llilc/compare/master...swaroop-sridhar:FP
