### ISSUE TITLE
Llvm log mangled due to multithreading

### ISSUE THREAD

**Issue by jashook** [dotnet/llilc#801]
Failed to read .... [Loadfield via helperSuccessfully read].

The output is non deterministic, it just happens when both threads output at the same time.

Note Ryujit seems to use printf which seems to take a lock internally.

**Comment by AndyAyersMS** [comment]
There is `SetUseAtomicWrites` available for `raw_ostreams` like `errs`, but it looks like for windows it may not do anything. So if we want to ensure this we'll probably need to set up a lock of our own.
