### ISSUE TITLE
Handle function pointers in indirect call

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#804]
LLILC is currently failing with an assertion when an indirect call to a function pointer is made.

The assertion failure is in llilc\lib\Reader\abisignature.cpp, line 317, at the beginning of the
ABICallSignature::emitCall method. 

This is in the context of a calli MSIL instruction. The Target is
 
  %67 = load %"(fnptr)"*, %"(fnptr)"** %arg3, align 8, !dbg !42
which is a function pointer value, whereas this assertion is expecting a pointer-sized
integer. 
 
%"(fnptr)" is defined as follows:
 
%"(fnptr)" = type <{ [8 x i8] }>
From some investigation is learned that "(fnptr)" is the name that the CoreClr uses to
denote function pointers. It seems to be describing function pointers as an opaque
vector of 8 bytes.

**Comment by AndyAyersMS** [comment]
@richardlford is there a test case for this ?

**Comment by pgavlin** [comment]
This sounds like #633; what did we miss in #805?

**Comment by richardlford** [comment]
I think these were the test cases (and yes, it was issue #633):

JIT\Methodical\casts\coverage\_il_dbgcastclass_calli.cmd
JIT\Methodical\casts\coverage\_il_dbgisinst_calli.cmd
JIT\Methodical\casts\coverage\_il_relcastclass_calli.cmd
JIT\Methodical\casts\coverage\_il_relisinst_calli.cmd
JIT\Methodical\casts\coverage\castclass_calli.cmd
JIT\Methodical\casts\coverage\isinst_calli.cmd

**Comment by AndyAyersMS** [comment]
So this is fixed now?

**Comment by richardlford** [comment]
Yes, it was fixed by #805. I guess closing this got missed. I'll close it now.
