### ISSUE TITLE
Verify we're not skipping methods in the enabled tests

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#821]
I asked a couple people and nobody could say for sure if we were skipping methods in the enabled tests. Seems like these days a 100% jit rate is a reasonable expectation.

So, we should make sure we're doing exactly this in our lab tests. @richardlford @russellhadley can one of you take this?

**Comment by richardlford** [comment]
@AndyAyersMS, I'll take this one.

**Comment by erozenfeld** [comment]
We are skipping some methods:
Found 2490 results
2490 tests, 967092 methods, 966528 good, 564 bad (99% good)
[Tail call]                                     492
[ckFinite]                                      38
[Direct unmanaged call]                         26
[unexpected type in load/store primitive]       8

**Comment by erozenfeld** [comment]
I'll take tail call since I already implemented jmp and it should be similar.

**Comment by AndyAyersMS** [comment]
Can you open issues for the others?

**Comment by erozenfeld** [comment]
I opened new issues and updated the existing ones:
[Tail call] #191
[ckFinite] #846 
[Direct unmanaged call] #499
[unexpected type in load/store primitive] #847

**Comment by AndyAyersMS** [comment]
@richardlford @russellhadley would be nice to get this done
