### ISSUE TITLE
Reader: implement ckfinite msil opcode

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#846]
We are skipping methods with ckfinite in the following tests:
JIT\IL_Conformance\Old\Conformance_Base\ldc_ckfinite_r4
JIT\IL_Conformance\Old\Conformance_Base\ldc_ckfinite_r8
JIT\Methodical\flowgraph\dev10_bug679053\flowgraph
JIT\Regression\clr-x64-JIT\v4.0\b602182\b602182
JIT\Regression\clr-x64-JIT\v4.0\b602182\b602182
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b11413\b11413
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b14591\b14591
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b15222\b15222
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b25459\b25459
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b27917\b27917
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b28522\b28522
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b31343\b31343
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b27873\b27873
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b40411\b40411
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b45985\b45985
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b73283\b73283
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b323557\b323557-dbg
JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b323557\b323557-ret
JIT\Regression\CLR-x86-JIT\V2.0-RTM\b489329\b489329
JIT\Regression\VS-ia64-JIT\M00\b108366\b108366
JIT\Regression\VS-ia64-JIT\M00\b109878\b109878
JIT\Regression\VS-ia64-JIT\M00\b85317\b85317
JIT\Regression\VS-ia64-JIT\M00\b92726\b92726

**Comment by AndyAyersMS** [comment]
I'll take this one.
