### ISSUE TITLE
New interop test causes assertion in the runtime

### ISSUE THREAD

**Issue by russellhadley** [dotnet/llilc#860]
Under the Win64 check build we're hitting an exception with the newly added interop test.  This issue is to track investigation.  To unblock testing I'm going to add an exclusion that references this issue.

Test path is: tests\src\Interop\NativeCallable\NativeCallableTest.cs

<snip>
Assert failure(PID 7144 [0x00001be8], Thread: 12220 [0x2fbc]): thread->PreemptiveGCDisabled()\r\n\r\nCORECLR! Thread::ObjectRefFlush + 0x42 (0x00007ffc`53956db2)\r\nCORECLR! PreStubWorker + 0x7F (0x00007ffc`53aaab7f)\r\nCORECLR! ThePreStub + 0x55 (0x00007ffc`53dc5fd5)\r\nUSER32! Ordinal2555 + 0x21B (0x00007ffc`6ab0a41b)\r\nUSER32! EnumWindows + 0x25 (0x00007ffc`6ab0a4b5)\r\n<no module>! <no symbol> + 0x0 (0x00007ffb`f4f51499)\r\n<no module>! <no symbol> + 0x0 (0x00000092`83e6cd68)\r\n<no module>! <no symbol> + 0x0 (0x00007ffb`f4af51a0)\r\n<no module>! <no symbol> + 0x0 (0x00000092`840ae4d0)\r\n<no module>! <no symbol> + 0x0 (0x00000101`00000001)\r\n    File: d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\vm\threads.cpp Line: 6858\r\n    Image: d:\j\workspace\dotnet_llilc_check_win64\coreclr\bin\Product\Windows_NT.x64.Debug\CoreRun.exe\r\n\r\n0x00007FFC6A82DFD2 (0x00007FFC548EDD10 0x0000009200001ACA 0x00007FFC54CA2030 0x0000000000000000), DebugBreak() + 0x2 bytes(s)\r\n0x00007FFC536A6B82 (0x00007FFC548EDD10 0x0000000000001ACA 0x00007FFC548F02D8 0x0000000000000000), DbgAssertDialog() + 0x2F2 bytes(s), d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\utilcode\debug.cpp, line 822\r\n0x00007FFC53956DB2 (0x00000092840AE4D0 0x00007FFC00000001 0x000000928408B3A0 0x0000000000000000), Thread::ObjectRefFlush() + 0x42 bytes(s), d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\vm\threads.cpp, line 6858 + 0x26 byte(s)\r\n0x00007FFC53AAAB7F (0x0000009283E6CBC8 0x00007FFBF4AF4C80 0x000000929E591BA4 0x0000000000000001), PreStubWorker() + 0x7F bytes(s), d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\vm\prestub.cpp, line 966\r\n0x00007FFC53DC5FD5 (0x0000000000060136 0x0000000000000000 0x000000000000FFFF 0x0000000000000001), ThePreStub() + 0x55 bytes(s), d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\vm\amd64\ThePreStubAMD64.asm, line 23\r\n0x00007FFC6AB0A41B (0x0000009283E6CD50 0x00007FFC6AB0A490 0x0000000000000000 0x0000000000000000), Ordinal2555() + 0x21B bytes(s)\r\n0x00007FFC6AB0A4B5 (0x0000009283E6CD68 0x00007FFBF4AF51A0 0x00000092840AE4D0 0x0000010100000001), EnumWindows() + 0x25 bytes(s)\r\n0x00007FFBF4F51499 (0x00007FFBF4AF51A0 0x00000092840AE4D0 0x0000010100000001 0x00000000000001CD) <unknown module>\r\n0x0000009283E6CD68 (0x00000092840AE4D0 0x0000010100000001 0x00000000000001CD 0x0000000000010000) <unknown module>\r\n0x00007FFBF4AF51A0 (0x0000010100000001 0x00000000000001CD 0x0000000000010000 0x00007FFC53C045B0) <unknown module>\r\n0x00000092840AE4D0 (0x00000000000001CD 0x0000000000010000 0x00007FFC53C045B0 0x00000092840AE4D0) <unknown module>\r\n0x0000010100000001 (0x0000000000010000 0x00007FFC53C045B0 0x00000092840AE4D0 0x00007FFC54CA8B04) <unknown module>\r\n0x00000000000001CD (0x00007FFC53C045B0 0x00000092840AE4D0 0x00007FFC54CA8B04 0x00007FFC6AB0A490) <unknown module>\r\n0x0000000000010000 (0x00000092840AE4D0 0x00007FFC54CA8B04 0x00007FFC6AB0A490 0x00007FFBF4AF5230) <unknown module>\r\n0x00007FFC53C045AF (0x00007FFC54CA8B04 0x00007FFC6AB0A490 0x00007FFBF4AF5230 0x00007FFBF4AF51E8), NDirectImportThunk() + 0x8F bytes(s), d:\j\workspace\dotnet_llilc_check_win64\coreclr\src\vm\amd64\AsmHelpers.asm, line 214 + 0x15 byte(s)\r\n0x00000092840AE4D0 (0x00007FFC6AB0A490 0x00007FFBF4AF5230 0x00007FFBF4AF51E8 0x0000000000000000) <unknown module>\r\n0x00007FFC54CA8B04 (0x00007FFBF4AF5230 0x00007FFBF4AF51E8 0x0000000000000000 0x00007FFBF4F500A8), g_TrapReturningThreads\r\n0x00007FFC6AB0A48F (0x00007FFBF4F51499 0x0000009283E6CD50 0x0000000000000000 0x0000000000000000), Ordinal2555() + 0x28F bytes(s)\r\n0x0000009283E6CCD0 (0x0000009283E6CD50 0x0000000000000000 0x0000000000000000 0x00007FFBF4F500A8) <unknown module>\r\n0x00007FFBF4F51499 (0x0000000000000000 0x0000000000000000 0x00007FFBF4F500A8 0x0000000000000000) <unknown module>\r\n0x0000009283E6CD50 (0x0000000000000000 0x00007FFBF4F500A8 0x0000000000000000 0x0000000000000000) <unknown module>\r\n\r\nRaw Output          :d:\j\workspace\dotnet_llilc_check_win64\coreclr\bin\tests\Windows_NT.x64.debug\Reports\Interop\NativeCallable\NativeCallableTest.output.txt\nTo Run the test     :Step 1. set Core_Root=d:\j\workspace\dotnet_llilc_check_win64\coreclr\bin\Product\Windows_NT.x64.Debug\n                     Step 2. d:\j\workspace\dotnet_llilc_check_win64\coreclr\bin\tests\Windows_NT.x64.debug\Interop\NativeCallable\NativeCallableTest.cmd\n 
</snip>

**Comment by tijoytom** [comment]
Just saw this one , i added the [NativeCallableMethod] support to CoreCLR . The assert that you are seeing is likely because some managed code is calling one of the methods in the test marked with [NativeCallable] attribute. Managed methods marked with  [NativeCallable] are not supposed to be called from managed code.
