### ISSUE TITLE
ReadyToRun optimization: use shared delay-load thunks

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/llilc#876]
LLILC currently uses non-shared delay-load thunks while RyuJIT uses shared delay-load thunks.

If the jit can generate a call in the form
`call [rel32]`
a shared delay-load thunk can be used.
Here is how it works by default in RyuJIT:

The DelayLoad_MethodCall helper that the indirection cell is pointing to initially needs to be able to determine the address of indirection cell.

```
            `call [indirection_cell]`
```

`indirection_cell:`
                `dq shared_delay_load_thunk`

`shared_delay_load_thunk:` // this is shared by all indirection cells
                `push 0` // this tells DelayLoad_MethodCall to disassemble the callsite to find address of the indirection cell
                ...
                `jmp DelayLoad_MethodCall`

In LLILC we don't guarantee `call [rel32]` form so here is how it works:

```
            `call …`
```

`indirection_cell:`
                `dq non-shared_delay_load_thunk`

`non_shared_delay_load_thunk:` // there is one of these for each target – less space efficient
                `push 0xXXXXX` // this tells DelayLoad_MethodCall the callsite address
                ...
                `jmp DelayLoad_MethodCall`

The way we tell the JIT-EE interface to return non-shared delay-load thunks is by passing CORINFO_ACCESS_ATYPICAL_CALLSITE to getFieldInfo, getCallInfo, and getReadyToRunHelper.

Possible solutions:
1. Use inline asm to guarantee call [rel32] form.
2. Use patchable code via patchpoints/statepoints to guarantee call [rel32] form.
3. Optimistically generate calls to shared delay-load thunks. When LLVM is done generating code inspect all calls and switch to non-shared delay-load thunks for calls that don't end up as call [rel32]. To increase the probability of calls being emitted in this form we should change the code to compute the call target right before creating the call instruction and after computing all args. I prototyped this and it definitely made a difference.

**Comment by redknightlois** [comment]
Awesome.
