### ISSUE TITLE
Linux: emit windows unwind information to report to CoreCLR

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#878]
The CoreCLR expects windows-style unwind codes for x64 codegen for all platforms. So when compiling for Linux we need to produce and convey these. This will likely require changes in LLVM and also in LLILC.

**Comment by AndyAyersMS** [comment]
@pgavlin might come in handy for linux testing

**Comment by pgavlin** [comment]
FWIW, I currently need to apply the patch at https://gist.github.com/pgavlin/76ad0b19dae00ff37ae9 in order to deal with the lack of Windows unwind codes in order for the Linux build to run successfully.
