### ISSUE TITLE
Roslyn failing in recent CI tests

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#951]
EG, [this one](http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_roslyn_test/90/).

@richardlford is this a known issue?

**Comment by richardlford** [comment]
@AndyAyersMS, these were passing before I tried removing our workaround to use EH. But then when I put things back they continued to fail. I've not investigated the cause.

**Comment by AndyAyersMS** [comment]
Looks like an assert I added is firing:
```
01:03:48.314      6>CoreCompile:
01:03:48.314          Assertion failed: (*NameToHandleMap)[Object->getName()] == ValueHandle && "value mismatch for function", file D:\j\workspace\dotnet_llilc_roslyn_test\LLVM\tools\llilc\lib\Reader\readerir.cpp, line 5897
```
This means we have two "symbol" names that are colliding.

**Comment by AndyAyersMS** [comment]
Looks like the test is still failing .... suspect it might be EH this time.
