### ISSUE TITLE
Sort includes per clang-format and fix resulting breaks

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/llilc#955]
I suppressed the clang-format sort-include check in #954. We should enable this and fix up our header usage to make it workable.

Each header should compile cleanly on its own, including all its necessary dependencies, this currently isn't the case for things like abi.h (and more).

**Comment by pgavlin** [comment]
> this currently isn't the case for things like abi.h

What's failing in abi.h?

**Comment by AndyAyersMS** [comment]
It has no `#includes` and refers to CLR and LLVM types, so it can't compile on its own, and must rely on some parent include.

Hence it's fragile in the face of header reordering.

**Comment by pgavlin** [comment]
> Hence it's fragile in the face of header reordering.

I see what you meant by "compile cleanly on its own." Personally, I disagree with this philosophy since it makes it more difficult to understand the dependencies of a particular piece of code, but I'll defer to clang-format.
