### ISSUE TITLE
Assertion: value mismatch for function.

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#961]
The following tests failed with 

Assertion failed: 
(*NameToHandleMap)[Object->getName()] == ValueHandle && "value mismatch for function", 
file d:\bm\x6\llvm\tools\llilc\lib\Reader\readerir.cpp, line 5909

*Tests*:
JIT\Regression\VS-ia64-JIT\V1.2-M01\b10827\b10827\b10827.cmd

This test failed when EH processing was enabled, but did not fail when
EH was not enabled.

**Comment by AndyAyersMS** [comment]
This should have been fixed by #958. Will investigate.

**Comment by AndyAyersMS** [comment]
Looks like it passes now, will enable.

**Comment by AndyAyersMS** [comment]
Actually this was never disabled, so nothing to do.
