### ISSUE TITLE
Assertion: Could not find cleanupret

### ISSUE THREAD

**Issue by richardlford** [dotnet/llilc#962]
Tests failed with:

Assertion failed: CleanupRetBlock && "Could not find cleanupret", 
file d:\bm\x6\llvm\tools\llilc\lib\Reader\readerir.cpp, line 625

Failing test:

JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b51875\b51875\b51875.cmd

This test failed when EH processing was enabled, but did not fail when
EH was not enabled.

**Comment by JosephTremoulet** [comment]
The cleanupret opcode is about to be removed from LLVM ([D15139](http://reviews.llvm.org/D15139)), at which point the asserting code will need to be rewritten; probably makes sense to wait to investigate this until then.
